"use client";
import { useEffect, useState } from "react";
import { Download, Eye, FileCode2, FileText, ShieldCheck } from "lucide-react";

type LinkInfo={competence:string;expiresAt:string;viewedAt:string|null};
export function ProtectedNote({token}:{token:string}){
  const [info,setInfo]=useState<LinkInfo|null>(null);const [error,setError]=useState("");const [opening,setOpening]=useState(false);const [opened,setOpened]=useState(false);
  useEffect(()=>{let active=true;void fetch(`/api/public/nfse/${token}`,{cache:"no-store"}).then(async response=>{const data=await response.json() as LinkInfo&{error?:string};if(!response.ok)throw new Error(data.error||"Link inválido.");if(active)setInfo(data)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Link inválido.")});return()=>{active=false}},[token]);
  async function open(){setOpening(true);setError("");try{const response=await fetch(`/api/public/nfse/${token}/open`,{method:"POST",cache:"no-store"});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"Não foi possível abrir a nota.");setOpened(true)}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível abrir a nota.")}finally{setOpening(false)}}
  const url=(format:"pdf"|"xml",disposition:"inline"|"attachment")=>`/api/public/nfse/${token}/document?format=${format}&disposition=${disposition}`;
  return <main className="protected-note-page"><section className="protected-note-card"><header><span><ShieldCheck/></span><div><small>JPI FISCAL</small><h1>NFS-e disponível</h1><p>Documento enviado com acesso individual protegido.</p></div></header>{error?<div className="protected-note-error">{error}</div>:!info?<div className="protected-note-loading">Verificando o link protegido…</div>:<><div className="protected-note-summary"><span>Competência</span><strong>{info.competence}</strong><small>O acesso será registrado somente após você tocar no botão abaixo.</small></div>{!opened?<button className="protected-note-open" disabled={opening} onClick={()=>void open()}><Eye/>{opening?"Abrindo com segurança…":"Visualizar NFS-e"}</button>:<div className="protected-note-files"><div><FileText/><span><strong>PDF da NFS-e</strong><small>Visualize ou baixe o documento.</small></span><a href={url("pdf","inline")} target="_blank" rel="noreferrer"><Eye/>Visualizar</a><a href={url("pdf","attachment")}><Download/>Baixar</a></div><div><FileCode2/><span><strong>XML da NFS-e</strong><small>Arquivo fiscal original.</small></span><a href={url("xml","inline")} target="_blank" rel="noreferrer"><Eye/>Visualizar</a><a href={url("xml","attachment")}><Download/>Baixar</a></div></div>}<p className="protected-note-footnote">Este link é pessoal. Não o encaminhe a terceiros.</p></>}</section></main>;
}
