"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, Clock3, Download, Eye, FileCode2, FileText, Filter, Mail, MailCheck, MessageCircle, RefreshCw, Search, Send, Settings, ShieldCheck, X } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase";
import type { AppPage, Role } from "./app-shell";

type DeliveryPayment={id:number;aluno_id:number;competencia:string;valor_nfse:number;status_nfse:string;alunos:{nome:string;responsavel:string;email:string|null;whatsapp:string|null;agenda_edu_student_id:string|null;agenda_edu_use_external_id:boolean}|null};
type DeliveryDocument={id:number;mensalidade_id:number;versao:number;chave_acesso:string;estado:string;emitida_em:string|null};
type DeliveryHistory={id:number;mensalidade_id:number;documento_homologacao_id:number;request_id:string;destinatario_pretendido:string;destinatario_utilizado:string;status:"enviando"|"enviado"|"erro";erro_mensagem:string|null;enviado_em:string|null;created_at:string};
type DeliveryRow={payment:DeliveryPayment;document:DeliveryDocument;latest?:DeliveryHistory};
type BatchStatus="waiting"|"sending"|"success"|"error";
type BatchMode="send"|"resend";
type BatchItem={row:DeliveryRow;status:BatchStatus;error?:string};
type DeliveryChannel="email"|"whatsapp"|"agenda-edu";
type WhatsAppInfo={ready:boolean;testRecipient:string|null;templateName:string};
type AgendaEduInfo={ready:boolean;environment:string;channelConfigured:boolean;message:string};
type DeliverySort="recent"|"student"|"value"|"sends";
const PAGE_SIZE=20;
const money=(value:number)=>Number(value).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR");

function Modal({onClose,title,subtitle,children}:{onClose:()=>void;title:string;subtitle:string;children:React.ReactNode}){return <div className="modal-backdrop"><div className="modal-card delivery-modal"><div className="modal-head"><div><h2>{title}</h2><p>{subtitle}</p></div><button className="icon-button" onClick={onClose} aria-label="Fechar"><X/></button></div>{children}</div></div>}

export function DeliveryCenter({role,accessToken,onNavigate}:{role:Role;accessToken:string|null;onNavigate:(page:AppPage)=>void}){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const canManage=role==="Administrador"||role==="Financeiro";
  const [channel,setChannel]=useState<DeliveryChannel>("email");
  const [rows,setRows]=useState<DeliveryRow[]>([]);const [history,setHistory]=useState<DeliveryHistory[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [message,setMessage]=useState("");
  const [query,setQuery]=useState("");const [statusFilter,setStatusFilter]=useState("pendente");const [competenceFilter,setCompetenceFilter]=useState("todas");const [sortOrder,setSortOrder]=useState<DeliverySort>("recent");const [page,setPage]=useState(1);const [selected,setSelected]=useState<Set<number>>(()=>new Set());
  const [modalOpen,setModalOpen]=useState(false);const [batch,setBatch]=useState<BatchItem[]>([]);const [batchMode,setBatchMode]=useState<BatchMode>("send");const [busy,setBusy]=useState(false);const inFlight=useRef(false);
  const [documentBusy,setDocumentBusy]=useState("");
  const [whatsappInfo,setWhatsappInfo]=useState<WhatsAppInfo|null>(null);
  const [agendaEduInfo,setAgendaEduInfo]=useState<AgendaEduInfo|null>(null);

  const load=useCallback(async()=>{
    if(!supabase)return;setLoading(true);setError("");
    const [paymentsResult,documentsResult,historyResult]=await Promise.all([
      supabase.from("mensalidades").select("id,aluno_id,competencia,valor_nfse,status_nfse,alunos(nome,responsavel,email,whatsapp,agenda_edu_student_id,agenda_edu_use_external_id)").order("created_at",{ascending:false}),
      supabase.from("nfse_documentos_homologacao").select("id,mensalidade_id,versao,chave_acesso,estado,emitida_em").eq("estado","ativa").order("versao",{ascending:false}),
      supabase.from("nfse_entregas").select("id,mensalidade_id,documento_homologacao_id,request_id,destinatario_pretendido,destinatario_utilizado,status,erro_mensagem,enviado_em,created_at").eq("canal",channel==="agenda-edu"?"agenda_edu":channel).eq("ambiente","homologacao").order("created_at",{ascending:false}),
    ]);
    if(paymentsResult.error||documentsResult.error||historyResult.error){setError(paymentsResult.error?.message||documentsResult.error?.message||historyResult.error?.message||"Não foi possível carregar as entregas.");setLoading(false);return}
    const payments=(paymentsResult.data||[]) as unknown as DeliveryPayment[];const documents=(documentsResult.data||[]) as DeliveryDocument[];const deliveries=(historyResult.data||[]) as DeliveryHistory[];
    const paymentById=new Map(payments.map(payment=>[payment.id,payment]));const latestByDocument=new Map<number,DeliveryHistory>();for(const delivery of deliveries)if(!latestByDocument.has(delivery.documento_homologacao_id))latestByDocument.set(delivery.documento_homologacao_id,delivery);
    setRows(documents.flatMap(document=>{const payment=paymentById.get(document.mensalidade_id);return payment?[{payment,document,latest:latestByDocument.get(document.id)}]:[]}));setHistory(deliveries);setLoading(false);
  },[channel,supabase]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(channel!=="whatsapp"||!accessToken){setWhatsappInfo(null);return}let active=true;void fetch("/api/deliveries/whatsapp",{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"}).then(async response=>{const data=await response.json().catch(()=>({})) as WhatsAppInfo&{error?:string};if(!response.ok)throw new Error(data.error||"Não foi possível verificar o WhatsApp.");if(active)setWhatsappInfo(data)}).catch(cause=>{if(active){setWhatsappInfo({ready:false,testRecipient:null,templateName:"envio_nfse"});setError(cause instanceof Error?cause.message:"Não foi possível verificar o WhatsApp.")}});return()=>{active=false}},[accessToken,channel]);
  useEffect(()=>{if(channel!=="agenda-edu"||!accessToken){setAgendaEduInfo(null);return}let active=true;void fetch("/api/deliveries/agenda-edu",{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"}).then(async response=>{const data=await response.json().catch(()=>({})) as AgendaEduInfo&{error?:string};if(!response.ok)throw new Error(data.error||"Não foi possível verificar a Agenda Edu.");if(active)setAgendaEduInfo(data)}).catch(cause=>{if(active){setAgendaEduInfo({ready:false,environment:"sandbox",channelConfigured:false,message:"A configuração da Agenda Edu ainda não está pronta."});setError(cause instanceof Error?cause.message:"Não foi possível verificar a Agenda Edu.")}});return()=>{active=false}},[accessToken,channel]);

  const sentAttemptsByDocument=useMemo(()=>{const attempts=new Map<number,DeliveryHistory[]>();for(const delivery of history){if(delivery.status!=="enviado")continue;const documentAttempts=attempts.get(delivery.documento_homologacao_id);if(documentAttempts)documentAttempts.push(delivery);else attempts.set(delivery.documento_homologacao_id,[delivery])}return attempts},[history]);
  const deliveryState=useCallback((row:DeliveryRow)=>{if(row.latest?.status==="enviando")return "enviando";if(sentAttemptsByDocument.has(row.document.id))return "enviado";return row.latest?.status||"pendente"},[sentAttemptsByDocument]);
  const competences=useMemo(()=>Array.from(new Set(rows.map(row=>row.payment.competencia))).sort((a,b)=>b.localeCompare(a,"pt-BR")),[rows]);
  const filtered=useMemo(()=>{const search=normalize(query.trim());const matches=rows.filter(row=>{const deliveryStatus=deliveryState(row);const haystack=normalize([row.payment.alunos?.nome,row.payment.alunos?.responsavel,row.payment.alunos?.email,row.payment.alunos?.whatsapp,row.payment.competencia,row.document.chave_acesso].filter(Boolean).join(" "));return(!search||haystack.includes(search))&&(statusFilter==="todas"||statusFilter===deliveryStatus)&&(competenceFilter==="todas"||row.payment.competencia===competenceFilter)});return matches.sort((a,b)=>sortOrder==="student"?(a.payment.alunos?.nome||"").localeCompare(b.payment.alunos?.nome||"","pt-BR"):sortOrder==="value"?Number(b.payment.valor_nfse)-Number(a.payment.valor_nfse):sortOrder==="sends"?(sentAttemptsByDocument.get(b.document.id)?.length||0)-(sentAttemptsByDocument.get(a.document.id)?.length||0):new Date(b.document.emitida_em||0).getTime()-new Date(a.document.emitida_em||0).getTime())},[competenceFilter,deliveryState,query,rows,sentAttemptsByDocument,sortOrder,statusFilter]);
  const pageCount=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));const safePage=Math.min(page,pageCount);const visibleRows=useMemo(()=>filtered.slice((safePage-1)*PAGE_SIZE,safePage*PAGE_SIZE),[filtered,safePage]);
  const selectedRows=useMemo(()=>filtered.filter(row=>selected.has(row.document.id)),[filtered,selected]);
  const recipientForRow=useCallback((row:DeliveryRow)=>channel==="agenda-edu"?row.payment.alunos?.agenda_edu_student_id:channel==="whatsapp"?row.payment.alunos?.whatsapp:row.payment.alunos?.email,[channel]);
  const selectableRows=useMemo(()=>filtered.filter(row=>deliveryState(row)!=="enviado"&&deliveryState(row)!=="enviando"&&Boolean(recipientForRow(row))&&(channel==="email"||channel==="whatsapp"&&Boolean(whatsappInfo?.ready)||channel==="agenda-edu"&&Boolean(agendaEduInfo?.ready))),[agendaEduInfo?.ready,channel,deliveryState,filtered,recipientForRow,whatsappInfo?.ready]);
  const sentCount=rows.filter(row=>deliveryState(row)==="enviado").length;const errorCount=rows.filter(row=>deliveryState(row)==="erro").length;const pendingCount=rows.length-sentCount-errorCount;
  function resetFilters(){setQuery("");setStatusFilter("pendente");setCompetenceFilter("todas");setSortOrder("recent");setPage(1)}
  function selectChannel(next:DeliveryChannel){if(busy)return;setChannel(next);setSelected(new Set());setMessage("");setError("");setStatusFilter("pendente");setPage(1)}
  function toggle(documentId:number){if(busy)return;setSelected(current=>{const next=new Set(current);if(next.has(documentId))next.delete(documentId);else next.add(documentId);return next})}
  function selectAll(){setSelected(new Set(selectableRows.map(row=>row.document.id)))}
  function openConfirmation(){if(!selectedRows.length)return;setError("");setMessage("");setBatchMode("send");setBatch(selectedRows.map(row=>({row,status:"waiting"})));setModalOpen(true)}
  function openResend(row:DeliveryRow){if(busy)return;setError("");setMessage("");setBatchMode("resend");setBatch([{row,status:"waiting"}]);setModalOpen(true)}
  function closeModal(){if(busy)return;setModalOpen(false);setBatch([]);setBatchMode("send")}
  async function runDelivery(targets:DeliveryRow[]){
    if(!accessToken||!targets.length||inFlight.current)return;inFlight.current=true;setBusy(true);setError("");setMessage("");const results:BatchItem[]=targets.map(row=>({row,status:"waiting"}));setBatch([...results]);
    for(const row of targets){const index=results.findIndex(item=>item.row.document.id===row.document.id);results[index]={row,status:"sending"};setBatch([...results]);try{const endpoint=channel==="agenda-edu"?"/api/deliveries/agenda-edu":channel==="whatsapp"?"/api/deliveries/whatsapp":"/api/deliveries/email";const response=await fetch(endpoint,{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({monthlyId:row.payment.id,documentId:row.document.id,requestId:crypto.randomUUID()}),cache:"no-store"});const data=await response.json().catch(()=>({})) as {ok?:boolean;error?:string};if(!response.ok||!data.ok)throw new Error(data.error||"O provedor não confirmou esta entrega.");results[index]={row,status:"success"}}catch(cause){results[index]={row,status:"error",error:cause instanceof Error?cause.message:"Não foi possível enviar."}}finally{setBatch([...results])}}
    const failures=results.filter(item=>item.status==="error");const successes=results.length-failures.length;const internalChannel=channel==="agenda-edu"?"Mensagens com os responsáveis":channel==="whatsapp"?"WhatsApp interno":"caixa interna";setSelected(new Set(failures.map(item=>item.row.document.id)));setStatusFilter(batchMode==="resend"?"enviado":"pendente");setMessage(failures.length?`Entrega concluída: ${successes} enviada(s) e ${failures.length} pendente(s).`:batchMode==="resend"?`NFS-e reenviada por ${internalChannel}. O histórico e o contador foram atualizados.`:`${successes} ${successes===1?"NFS-e de teste enviada":"NFS-e de teste enviadas"} por ${internalChannel}.`);await load();inFlight.current=false;setBusy(false);
  }
  async function handleDocument(documentId:number,format:"pdf"|"xml",disposition:"inline"|"attachment"){
    if(!accessToken||documentBusy)return;
    const actionKey=`${documentId}-${format}-${disposition}`;const preview=disposition==="inline"?window.open("","_blank"):null;
    if(preview)preview.opener=null;
    setDocumentBusy(actionKey);setError("");
    try{
      const params=new URLSearchParams({documentId:String(documentId),format,disposition});
      const response=await fetch(`/api/deliveries/documents?${params}`,{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"});
      if(!response.ok){const data=await response.json().catch(()=>({})) as {error?:string};throw new Error(data.error||"O documento não pôde ser aberto.")}
      const blob=await response.blob();const url=URL.createObjectURL(blob);
      if(disposition==="inline"){
        if(preview)preview.location.href=url;else window.open(url,"_blank","noopener,noreferrer");
      }else{
        const anchor=document.createElement("a");anchor.href=url;anchor.download=response.headers.get("Content-Disposition")?.match(/filename="([^"]+)"/)?.[1]||`nfse.${format}`;document.body.appendChild(anchor);anchor.click();anchor.remove();
      }
      window.setTimeout(()=>URL.revokeObjectURL(url),60_000);
    }catch(cause){preview?.close();setError(cause instanceof Error?cause.message:"Não foi possível acessar o documento.")}
    finally{setDocumentBusy("")}
  }
  const batchDone=batch.length>0&&batch.every(item=>item.status==="success"||item.status==="error");const batchErrors=batch.filter(item=>item.status==="error");
  const isWhatsapp=channel==="whatsapp";const isAgendaEdu=channel==="agenda-edu";const channelReady=channel==="email"||isWhatsapp&&Boolean(whatsappInfo?.ready)||isAgendaEdu&&Boolean(agendaEduInfo?.ready);const internalRecipient=isAgendaEdu?"responsáveis vinculados ao aluno no Sandbox":isWhatsapp?(whatsappInfo?.testRecipient||"número interno configurado"):"administracao@jejoaopaulo.com.br";const channelLabel=isAgendaEdu?"Agenda Edu":isWhatsapp?"WhatsApp":"e-mail";

  return <div className="delivery-page">
    <div className="page-heading"><div><span className="eyebrow">COMUNICAÇÕES</span><h1>Enviar notas</h1><p>Escolha o canal para encaminhar as NFS-e aos responsáveis.</p></div><div className="delivery-heading-icon"><MailCheck/></div></div>
    <section className="delivery-channels" aria-label="Canais para envio de notas"><button className={channel==="email"?"active email":"email"} onClick={()=>selectChannel("email")}><span><Mail/></span><div><strong>Enviar por e-mail</strong><small>Locaweb conectada</small></div></button><button className={channel==="whatsapp"?"active whatsapp":"whatsapp"} onClick={()=>selectChannel("whatsapp")}><span><MessageCircle/></span><div><strong>WhatsApp</strong><small>{whatsappInfo?.ready?"Meta conectada":"Meta Cloud API"}</small></div></button><button className={channel==="agenda-edu"?"active agenda":"agenda"} onClick={()=>selectChannel("agenda-edu")}><span><CalendarDays/></span><div><strong>Agenda Edu</strong><small>Canal escolar</small></div></button></section>
    <>
    <div className="notice warning"><ShieldCheck/><div><strong>Modo seguro de homologação</strong><span>{isAgendaEdu?<>Cada teste usa <b>Mensagens com os responsáveis</b> no Sandbox, em canal somente de leitura. O PDF e o XML seguem em duas mensagens consecutivas porque a API aceita um anexo por mensagem.</>:<>O responsável aparece para conferência, mas todos os testes por {channelLabel} são enviados somente para <b>{internalRecipient}</b>. As famílias não receberão documentos sem validade fiscal.{isWhatsapp&&" O PDF segue anexado e o XML por um link privado válido por 7 dias."}</>}</span></div></div>
    {isWhatsapp&&whatsappInfo&&!whatsappInfo.ready&&<div className="notice compact"><Settings/><div><strong>Configuração necessária</strong><span>Cadastre e teste a Meta Cloud API e o número interno de homologação antes do primeiro envio.</span>{role==="Administrador"&&<button type="button" className="secondary" onClick={()=>onNavigate("Configurações")}>Abrir configuração do WhatsApp</button>}</div></div>}
    {isAgendaEdu&&agendaEduInfo&&!agendaEduInfo.ready&&<div className="notice compact"><Settings/><div><strong>Configuração necessária</strong><span>{agendaEduInfo.message} Vincule também o ID da Agenda Edu aos alunos.</span>{role==="Administrador"&&<button type="button" className="secondary" onClick={()=>onNavigate("Configurações")}>Abrir configuração da Agenda Edu</button>}</div></div>}
    {error&&<div className="error-box page-error">{error}</div>}{message&&<div className="success-box">{message}</div>}
    <section className="delivery-stats"><article><span>Pendentes</span><strong>{pendingCount}</strong><small>Aguardando teste</small></article><article><span>Enviadas</span><strong>{sentCount}</strong><small>{isWhatsapp?"WhatsApp interno":"Caixa interna"}</small></article><article><span>Com erro</span><strong>{errorCount}</strong><small>Disponíveis para repetir</small></article><article><span>Histórico</span><strong>{history.length}</strong><small>Tentativas por {channelLabel}</small></article></section>
    <section className="delivery-toolbar"><div className="search-input"><Search/><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder={`Buscar aluno, responsável, ${isWhatsapp?"WhatsApp":"e-mail"} ou chave`}/></div><label><Filter/><select aria-label="Filtrar por situação" value={statusFilter} onChange={event=>{setStatusFilter(event.target.value);setPage(1)}}><option value="todas">Todas as situações</option><option value="pendente">Pendentes</option><option value="enviado">Enviadas</option><option value="erro">Com erro</option><option value="enviando">Em andamento</option></select></label><label><CalendarDays/><select aria-label="Filtrar por competência" value={competenceFilter} onChange={event=>{setCompetenceFilter(event.target.value);setPage(1)}}><option value="todas">Todas as competências</option>{competences.map(competence=><option key={competence} value={competence}>{competence}</option>)}</select></label><label><ChevronDown/><select aria-label="Ordenar notas" value={sortOrder} onChange={event=>{setSortOrder(event.target.value as DeliverySort);setPage(1)}}><option value="recent">Mais recentes</option><option value="student">Aluno A–Z</option><option value="value">Maior valor</option><option value="sends">Mais enviadas</option></select></label><button type="button" className="delivery-clear-filters" onClick={resetFilters}>Limpar filtros</button></section>
    <section className="delivery-results-summary"><div><strong>{filtered.length}</strong><span>{filtered.length===1?"nota encontrada":"notas encontradas"}</span></div><small>Mostrando {filtered.length?((safePage-1)*PAGE_SIZE)+1:0}–{Math.min(safePage*PAGE_SIZE,filtered.length)} de {filtered.length}</small></section>
    {canManage&&channelReady&&selectableRows.length>0&&<section className="delivery-batch-bar"><div><strong>{selectedRows.length}</strong><span>selecionadas</span></div><button className="text-button" disabled={busy} onClick={selectAll}>Selecionar todas ({selectableRows.length})</button><button className="text-button" disabled={busy||!selected.size} onClick={()=>setSelected(new Set())}>Limpar</button><button className="primary" disabled={busy||!selectedRows.length} onClick={openConfirmation}><Send size={17}/>Enviar selecionadas</button></section>}
    {loading?<div className="empty-state"><strong>Carregando entregas…</strong></div>:filtered.length===0?<div className="empty-state"><MailCheck/><strong>Nenhuma NFS-e encontrada</strong><p>Ajuste os filtros ou limpe a busca para visualizar outras notas.</p><button type="button" className="secondary" onClick={resetFilters}>Limpar filtros</button></div>:<div className="delivery-list">{visibleRows.map(row=>{const latest=row.latest;const state=deliveryState(row);const recipient=recipientForRow(row);const sentAttempts=sentAttemptsByDocument.get(row.document.id)||[];const lastSuccessfulAttempt=sentAttempts[0];return <article key={row.document.id} className={`delivery-row ${state}`}>
      {canManage&&state!=="enviado"?<input type="checkbox" checked={selected.has(row.document.id)} disabled={busy||!channelReady||!recipient||state==="enviando"} onChange={()=>toggle(row.document.id)} aria-label={`Selecionar ${row.payment.alunos?.nome||"aluno"}`}/>:<span className="delivery-selection-spacer" aria-hidden="true"/>}<div className="delivery-main"><strong>{row.payment.alunos?.nome||`Aluno #${row.payment.aluno_id}`}</strong><span>{row.payment.alunos?.responsavel||"Responsável não informado"}</span><small>{recipient||(isWhatsapp?"WhatsApp do responsável não informado":"E-mail do responsável não informado")}</small></div><div className="delivery-document"><div className="delivery-chips"><span>{row.payment.competencia}</span><b>{money(row.payment.valor_nfse)}</b>{sentAttempts.length>0&&<em>{sentAttempts.length} {sentAttempts.length===1?"envio":"envios"}</em>}</div><small>Versão {row.document.versao} · Chave {row.document.chave_acesso.slice(0,8)}…{row.document.chave_acesso.slice(-6)}</small></div><div className={`delivery-status ${state}`}>{state==="enviado"?<Check/>:state==="erro"?<X/>:<Clock3/>}<span><strong>{state==="enviado"?"Enviada":state==="erro"?"Falhou":state==="enviando"?"Enviando":"Pendente"}</strong><small>{state==="enviado"&&lastSuccessfulAttempt?.enviado_em?new Date(lastSuccessfulAttempt.enviado_em).toLocaleString("pt-BR"):latest?.erro_mensagem||"Aguardando envio"}</small></span></div>
      {state==="enviado"&&<details className="delivery-details"><summary><span>Documentos e histórico</span><small>PDF, XML e reenvio</small><ChevronDown/></summary><div className="delivery-details-content"><div className="delivery-files"><div><span><FileText/><strong>PDF</strong></span><button type="button" disabled={Boolean(documentBusy)} onClick={()=>void handleDocument(row.document.id,"pdf","inline")}><Eye/>Visualizar</button><button type="button" disabled={Boolean(documentBusy)} onClick={()=>void handleDocument(row.document.id,"pdf","attachment")}><Download/>Baixar</button></div><div><span><FileCode2/><strong>XML</strong></span><button type="button" disabled={Boolean(documentBusy)} onClick={()=>void handleDocument(row.document.id,"xml","inline")}><Eye/>Visualizar</button><button type="button" disabled={Boolean(documentBusy)} onClick={()=>void handleDocument(row.document.id,"xml","attachment")}><Download/>Baixar</button></div></div><div className="delivery-resend"><div><MailCheck/><span><strong>Enviada {sentAttempts.length} {sentAttempts.length===1?"vez":"vezes"}</strong><small>Último envio: {lastSuccessfulAttempt?.enviado_em?new Date(lastSuccessfulAttempt.enviado_em).toLocaleString("pt-BR"):"data não informada"} · {lastSuccessfulAttempt?.destinatario_utilizado}</small>{latest?.status==="erro"&&<small className="delivery-resend-error">Última tentativa falhou: {latest.erro_mensagem}</small>}</span></div>{canManage&&channelReady&&<button type="button" className="secondary" disabled={busy} onClick={()=>openResend(row)}><RefreshCw size={16}/>Reenviar pelo {channelLabel}</button>}</div></div></details>}
    </article>})}</div>}
    {!loading&&filtered.length>PAGE_SIZE&&<nav className="delivery-pagination" aria-label="Paginação das notas"><button type="button" className="secondary" disabled={safePage===1} onClick={()=>setPage(current=>Math.max(1,current-1))}><ChevronLeft/>Anterior</button><span>Página <strong>{safePage}</strong> de {pageCount}</span><button type="button" className="secondary" disabled={safePage===pageCount} onClick={()=>setPage(current=>Math.min(pageCount,current+1))}>Próxima<ChevronRight/></button></nav>}
    {modalOpen&&<Modal onClose={closeModal} title={batchMode==="resend"?`Reenviar NFS-e pelo ${channelLabel}`:`Enviar NFS-e de teste por ${channelLabel}`} subtitle={isWhatsapp?"PDF anexado · XML em link privado de 7 dias":"PDF e XML anexados · fila segura de homologação"}><div className="delivery-modal-body"><div className="notice warning"><ShieldCheck/><div><strong>{batchMode==="resend"?"Confirme o reenvio":"Confirme o teste interno"}</strong><span>{batchMode==="resend"?`Esta nota já foi enviada ${sentAttemptsByDocument.get(batch[0]?.row.document.id)?.length||0} vez(es). Um novo envio será registrado sem apagar o histórico anterior.`:`${batch.length} ${batch.length===1?"documento será enviado":"documentos serão enviados"} separadamente para ${internalRecipient}, ${isWhatsapp?"com o PDF anexado e um link privado do XML":"com o PDF e o XML de homologação anexados"}.`}</span></div></div>{batchMode==="resend"&&<div className="notice compact">{isWhatsapp?<MessageCircle/>:<Mail/>}<span>Na homologação, o reenvio irá somente para <b>{internalRecipient}</b>. O contato do responsável aparece abaixo apenas para conferência.</span></div>}{busy&&<div className="delivery-progress"><strong>Enviando e registrando</strong><span>{batch.filter(item=>item.status==="success"||item.status==="error").length} de {batch.length}</span><progress max={Math.max(batch.length,1)} value={batch.filter(item=>item.status==="success"||item.status==="error").length}/></div>}<div className="nfse-batch-results">{batch.map(item=><div key={item.row.document.id} className={`nfse-batch-result ${item.status}`}><span className="nfse-batch-result-icon">{item.status==="success"?<Check/>:item.status==="error"?<X/>:item.status==="sending"?<RefreshCw/>:<Clock3/>}</span><span><strong>{item.row.payment.alunos?.nome||"Aluno"}</strong><small>{recipientForRow(item.row)||(isWhatsapp?"Sem WhatsApp cadastrado":"Sem e-mail cadastrado")}</small>{item.error&&<small>{item.error}</small>}</span><b>{item.status==="success"?"Enviada":item.status==="error"?"Pendente":item.status==="sending"?"Enviando":"Aguardando"}</b></div>)}</div><div className="form-actions"><button className="secondary" disabled={busy} onClick={closeModal}>{batchDone?"Fechar":"Cancelar"}</button>{!busy&&!batchDone&&<button className="primary" onClick={()=>void runDelivery(batch.map(item=>item.row))}>{batchMode==="resend"?<RefreshCw size={17}/>:<Send size={17}/>} {batchMode==="resend"?"Confirmar reenvio":"Confirmar e enviar"}</button>}{!busy&&batchDone&&batchErrors.length>0&&<button className="primary" onClick={()=>void runDelivery(batchErrors.map(item=>item.row))}><RefreshCw size={17}/>Repetir pendentes</button>}</div></div></Modal>}
    </>
  </div>;
}
