"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {Check,Clock3,Copy,Globe2,RefreshCw,ShieldCheck} from "lucide-react";
import {authenticatedFetch} from "@/lib/authenticated-fetch";

type Provider="locaweb"|"registro_br";
type Config={current_domain:string;base_domain:string|null;subdomain:string;desired_domain:string|null;dns_provider:Provider;dns_type:string;dns_target:string;status:string;last_dns_value:string|null;last_checked_at:string|null};
type History={id:number;action:string;requested_domain:string|null;dns_value:string|null;status:string;details:string|null;created_at:string;created_by_email:string|null};
const statusLabel:Record<string,string>={nao_configurado:"Não configurado",planejado:"Planejado",aguardando_dns:"Aguardando Locaweb",dns_confirmado:"DNS confirmado",ativo:"Ativo",erro:"Erro"};

export function DomainSettings({accessToken}:{accessToken:string|null}){
  const [config,setConfig]=useState<Config|null>(null);const [history,setHistory]=useState<History[]>([]);const [provider,setProvider]=useState<Provider>("locaweb");const [baseDomain,setBaseDomain]=useState("");const [subdomain,setSubdomain]=useState("fiscal");const [busy,setBusy]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");
  const request=useCallback(async(init?:RequestInit)=>{if(!accessToken)throw new Error("Sessão indisponível.");const response=await authenticatedFetch("/api/admin/domain-settings",{...init,headers:{Authorization:`Bearer ${accessToken}`,...init?.headers},cache:"no-store"});const data=await response.json().catch(()=>({})) as {error?:string;config?:Config;history?:History[];confirmed?:boolean;dnsValue?:string;status?:string;checkedAt?:string};if(!response.ok)throw new Error(data.error||"Não foi possível acessar a configuração de domínio.");return data},[accessToken]);
  const load=useCallback(async()=>{try{setError("");const data=await request();if(data.config){setConfig(data.config);setProvider(data.config.dns_provider||"locaweb");setBaseDomain(data.config.base_domain||"");setSubdomain(data.config.subdomain||"fiscal")}setHistory(data.history||[])}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível carregar o domínio.")}},[request]);
  useEffect(()=>{void load()},[load]);
  async function save(event:FormEvent){event.preventDefault();setBusy("save");setError("");setMessage("");try{const data=await request({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save",provider,baseDomain,subdomain})});if(data.config)setConfig(data.config);setMessage(`Planejamento salvo para ${provider==="registro_br"?"Registro.br":"Locaweb"}. Nenhum DNS foi alterado.`);await load()}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível salvar.")}finally{setBusy("")}}
  async function verify(){setBusy("verify");setError("");setMessage("");try{const data=await request({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"verify"})});setMessage(data.confirmed?"Apontamento confirmado. O domínio já está direcionado para a Vercel.":`O apontamento ainda não apareceu. Resultado: ${data.dnsValue||"nenhum CNAME"}.`);await load()}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível verificar.")}finally{setBusy("")}}
  const desired=`${subdomain||"fiscal"}.${baseDomain||"seudominio.com.br"}`;
  const copy=async(value:string)=>{await navigator.clipboard.writeText(value);setMessage(`Copiado: ${value}`)};
  return <div className="domain-settings">
    <section className="panel domain-current-card"><div className="domain-card-icon"><Globe2/></div><div><span>ENDEREÇO OFICIAL ATUAL</span><strong>{config?.current_domain||"jpi-fiscal.vercel.app"}</strong><small>Este endereço continuará funcionando durante toda a preparação.</small></div><b className="status ativo">ATIVO</b></section>
    {error&&<div className="error-box">{error}</div>}{message&&<div className="success-box"><Check size={17}/>{message}</div>}
    <div className="domain-settings-grid">
      <form className="panel data-form domain-plan-card" onSubmit={save}><div className="panel-title"><div><h2>Novo endereço personalizado</h2><p>Escolha onde o domínio é administrado e informe o endereço.</p></div><Globe2/></div><label>Provedor do domínio<select value={provider} onChange={event=>setProvider(event.target.value as Provider)}><option value="locaweb">Locaweb</option><option value="registro_br">Registro.br</option></select></label><label>Domínio registrado no provedor<input value={baseDomain} onChange={event=>setBaseDomain(event.target.value.toLowerCase())} placeholder="exemplo.com.br" required/></label><label>Nome do subdomínio<input value={subdomain} onChange={event=>setSubdomain(event.target.value.toLowerCase().replace(/[^a-z0-9-]/g,""))} placeholder="fiscal" required/></label><div className="domain-preview"><span>Novo endereço planejado</span><strong>{desired}</strong></div><div className="notice warning compact"><ShieldCheck/><span>Salvar aqui não altera site, e-mail ou DNS. Apenas prepara e registra o procedimento.</span></div><button className="primary" disabled={Boolean(busy)}>{busy==="save"?"Salvando…":"Salvar planejamento"}</button></form>
      <section className="panel domain-dns-card"><div className="panel-title"><div><h2>Apontamento no {provider==="registro_br"?"Registro.br":"Locaweb"}</h2><p>Crie somente este registro na Zona de DNS.</p></div><span className={`status ${config?.status==="dns_confirmado"?"ativo":"pendente"}`}>{statusLabel[config?.status||"nao_configurado"]}</span></div><div className="domain-dns-record"><div><span>TIPO</span><strong>CNAME</strong></div><div><span>NOME / HOST</span><strong>{config?.subdomain||subdomain||"fiscal"}</strong><button type="button" onClick={()=>void copy(config?.subdomain||subdomain||"fiscal")}><Copy/>Copiar</button></div><div><span>DESTINO</span><strong>{config?.dns_target||"cname.vercel-dns-0.com"}</strong><button type="button" onClick={()=>void copy(config?.dns_target||"cname.vercel-dns-0.com")}><Copy/>Copiar</button></div></div><div className="domain-instructions"><strong>{provider==="registro_br"?"No painel do Registro.br":"Na Central da Locaweb"}</strong><ol><li>{provider==="registro_br"?"Abra o domínio e entre em DNS → Configurar zona DNS.":"Abra Domínios e Zona de DNS."}</li><li>Escolha o domínio <b>{config?.base_domain||baseDomain||"informado acima"}</b>.</li><li>Adicione o CNAME exatamente como mostrado.</li><li>Não altere registros MX, SPF, DKIM ou DMARC do e-mail.</li><li>Volte aqui e clique em verificar.</li></ol></div><button type="button" className="secondary" onClick={()=>void verify()} disabled={Boolean(busy)||!config?.desired_domain}><RefreshCw size={16}/>{busy==="verify"?"Verificando…":"Verificar apontamento"}</button>{config?.last_checked_at&&<small className="domain-last-check"><Clock3/>Última verificação: {new Date(config.last_checked_at).toLocaleString("pt-BR")} · {config.last_dns_value}</small>}</section>
    </div>
    <section className="panel domain-history"><div className="panel-title"><div><h2>Histórico do domínio</h2><p>Registro de todas as preparações e verificações feitas pelo Master.</p></div></div>{history.length?<div>{history.map(item=><article key={item.id}><span className={`status ${item.status==="dns_confirmado"?"ativo":"pendente"}`}>{statusLabel[item.status]||item.status}</span><div><strong>{item.requested_domain||"Domínio não informado"}</strong><small>{item.details}</small></div><time>{new Date(item.created_at).toLocaleString("pt-BR")}</time></article>)}</div>:<div className="empty-state compact"><Globe2/><strong>Nenhuma alteração registrada</strong><p>O primeiro planejamento aparecerá aqui.</p></div>}</section>
  </div>
}
