"use client";

import { useMemo, useState } from "react";
import { BookOpen, CheckCircle2, FileCheck2, GraduationCap, HelpCircle, KeyRound, Mail, MailCheck, MessageCircle, Search, Settings, ShieldCheck, Sparkles, UsersRound, WalletCards } from "lucide-react";

type Destination = "Painel"|"Alunos e Responsáveis"|"Mensalidades"|"Assistente de emissão"|"NFS-e"|"Ajustes NFS-e"|"Enviar notas"|"Configurações";
type Guide = {
  id:string;
  title:string;
  category:string;
  description:string;
  icon:typeof BookOpen;
  destination?:Destination;
  steps:string[];
  notes?:string[];
};

const guides:Guide[]=[
  {id:"visao-geral",title:"Fluxo recomendado para começar do zero",category:"Começando",description:"Ordem segura para preparar, emitir e entregar as notas sem pular etapas.",icon:CheckCircle2,destination:"Assistente de emissão",steps:["Confira no Painel se a base SWeduc carregou os alunos esperados.","Em Configurações, confira empresa, certificado A1, e-mail, WhatsApp e Agenda Edu.","No Assistente de emissão, busque o aluno pela SWeduc e confirme o responsável financeiro correto.","Complete cadastro, CPF/CNPJ, e-mail, WhatsApp e endereço do responsável antes da NFS-e.","Crie a mensalidade, revise competência, vencimento, valor e descrição do serviço.","Gere a DPS, confira a prévia, envie à SEFIN e só depois entregue por e-mail, WhatsApp ou Agenda Edu."],notes:["Não altere certificado, credenciais ou permissões durante uma emissão em andamento.","Se aparecer cadastro incompleto, corrija antes de enviar para a SEFIN."]},
  {id:"painel",title:"Painel",category:"Painel",description:"Resumo da operação, alunos carregados da SWeduc e situação dos envios.",icon:BookOpen,destination:"Painel",steps:["Use o card Alunos na SWeduc para confirmar quantos alunos estão no espelho local.","Confira a data da última atualização da API/SWedUC.","Veja mensalidades abertas, pagas e notas revisadas.","Acompanhe os totais de envio por e-mail, WhatsApp e Agenda Edu.","Clique em Atualizar se acabou de importar alunos ou limpar testes."],notes:["O card da SWeduc mostra a base espelhada no banco, não apenas os alunos que já viraram cadastro fiscal."]},
  {id:"sweduc",title:"Espelho SWeduc",category:"SWeduc",description:"Como usar os dados da SWeduc para carregar alunos mais rápido.",icon:GraduationCap,destination:"Assistente de emissão",steps:["Use Buscar aluno na SWeduc dentro do Assistente ou em Alunos e Responsáveis.","Filtre por ano letivo, segmento, série e turma, ou pesquise pelo nome.","Ao selecionar o aluno, confira os responsáveis retornados pela SWeduc.","Escolha o responsável financeiro correto antes de preparar a nota.","O aluno só é gravado no cadastro fiscal quando você inicia a emissão."],notes:["O espelho SWeduc fica mantido para consulta rápida e não é apagado nas limpezas operacionais.","Se a SWeduc mudar dados do responsável, atualize o cadastro fiscal antes da próxima emissão."]},
  {id:"alunos",title:"Alunos e responsáveis",category:"Cadastros",description:"Dados que precisam estar completos para a nota sair corretamente.",icon:UsersRound,destination:"Alunos e Responsáveis",steps:["Abra o cadastro do aluno antes de emitir quando houver alerta vermelho.","Preencha responsável financeiro, CPF/CNPJ, e-mail e WhatsApp.","Complete CEP, logradouro, número, complemento quando houver, bairro, cidade e UF.","Para Rio de Janeiro, mantenha UF como RJ e cidade como Rio de Janeiro.","Clique em Salvar alterações e volte ao Assistente ou NFS-e para continuar.","Quando o mesmo responsável tiver mais de um aluno, o sistema sincroniza os dados pelo CPF/CNPJ."],notes:["Campos vazios ficam sinalizados em vermelho porque podem impedir XML/PDF completo da NFS-e.","O endereço do responsável financeiro é enviado no XML quando estiver completo."]},
  {id:"mensalidades",title:"Mensalidades",category:"Financeiro",description:"Criação da cobrança que será usada na emissão fiscal.",icon:WalletCards,destination:"Mensalidades",steps:["Selecione o aluno cadastrado ou carregado pela SWeduc.","Informe competência, valor e status do pagamento.","Confira o vencimento vindo da SWeduc quando disponível.","Revise a descrição do serviço antes de gerar a DPS.","Se a nota foi cancelada, crie/continue uma nova emissão sem reaproveitar a chave antiga."],notes:["Depois de emitir uma NFS-e ativa, valor e descrição só devem mudar por cancelamento ou substituição fiscal."]},
  {id:"assistente",title:"Assistente de emissão",category:"Emissão",description:"Fluxo guiado para criar mensalidade, validar cadastro, gerar XML e abrir a SEFIN.",icon:Sparkles,destination:"Assistente de emissão",steps:["Comece em Nova emissão e escolha o aluno na SWeduc.","Confirme o responsável financeiro e complete os dados obrigatórios.","Crie a mensalidade e avance pelas etapas de validação, DPS, prévia e XML.","Quando chegar na etapa SEFIN, abra o módulo NFS-e oficial para transmitir.","Após a emissão, volte ao Assistente para entregar a nota ao responsável.","Se uma NFS-e for cancelada, ela deixa de contar como emitida e fica livre para nova emissão."],notes:["O Assistente usa os mesmos módulos oficiais por trás; ele apenas organiza a sequência.","Não envie ao responsável enquanto a nota não estiver ativa na SEFIN."]},
  {id:"nfse",title:"NFS-e",category:"NFS-e",description:"Preparação, validação, transmissão e visualização de PDF/XML.",icon:FileCheck2,destination:"NFS-e",steps:["Valide os dados fiscais da mensalidade.","Abra a prévia da DPS e confira tomador, serviço, competência, valor e tributos.","Guarde o XML da DPS no sistema.","Clique em Enviar à SEFIN quando estiver pronto.","Depois do retorno, visualize o DANFSe em PDF e o XML oficial.","Se houver rejeição, leia a mensagem, corrija o cadastro ou DPS e tente novamente."],notes:["A NFS-e oficial mantém logo, QR Code, chave de acesso e XML conforme retorno da SEFIN.","Notas canceladas não devem aparecer como emitidas para envio."]},
  {id:"ajustes",title:"Ajustes NFS-e",category:"NFS-e",description:"Cancelamento, substituição e histórico de versões.",icon:FileCheck2,destination:"Ajustes NFS-e",steps:["Use Cancelar NFS-e quando a nota não deve mais valer.","Ao cancelar, informe motivo claro e aguarde confirmação da SEFIN.","A nota cancelada fica em vermelho e sai da mensalidade ativa para permitir nova emissão.","Use substituição quando precisar trocar uma nota ativa por outra com correção fiscal.","Abra o histórico para conferir versões ativas, substituídas e canceladas."],notes:["Cancelamento e substituição preservam histórico; não apagam a trilha fiscal.","Após cancelar, o envio ao responsável só deve acontecer depois da nova NFS-e ativa."]},
  {id:"entregas",title:"Enviar notas",category:"Comunicações",description:"Entrega por e-mail, WhatsApp manual e Agenda Edu.",icon:MailCheck,destination:"Enviar notas",steps:["Escolha o canal: E-mail, WhatsApp ou Agenda Edu.","A lista mostra apenas documentos ativos disponíveis para entrega.","Confira destinatário antes de enviar: e-mail, número WhatsApp ou aluno/canal Agenda Edu.","Use Copiar mensagem quando for Agenda Edu e cole no canal correto.","Abra Documentos e histórico para ver PDF, XML e tentativas anteriores.","Reenvios registram nova tentativa sem apagar histórico."],notes:["O e-mail envia PDF e XML anexados ao responsável cadastrado na nota.","WhatsApp abre WhatsApp Web/app com o número do responsável e link seguro.","Agenda Edu usa mensagem manual com link seguro para PDF e XML."]},
  {id:"configuracoes",title:"Configurações",category:"Configurações",description:"Empresa, certificado, integrações e permissões.",icon:Settings,destination:"Configurações",steps:["Em Empresa, confira CNPJ, inscrição municipal, razão social, regime, PIS e COFINS.","Em Certificado A1, mantenha arquivo válido e senha guardada no cofre.","Em Integrações, configure SWeduc, e-mail, WhatsApp e Agenda Edu.","Em Usuários e Permissões, libere apenas os módulos necessários para cada perfil.","Teste conexões antes de iniciar emissão real."],notes:["Não envie senhas, tokens ou certificado por chat, e-mail ou WhatsApp.","Alterações fiscais devem ser conferidas com a contabilidade."]},
  {id:"email",title:"E-mail",category:"Comunicações",description:"O que conferir quando o envio por e-mail não chega ao responsável.",icon:Mail,destination:"Configurações",steps:["Confira se o e-mail do responsável está correto no cadastro do aluno.","Verifique em Configurações se SMTP/Locaweb está salvo e conectado.","Envie um teste da integração antes de disparar notas reais.","Confira spam/lixo eletrônico no destinatário.","Se trocar a senha do webmail, atualize a senha no JPI Fiscal."],notes:["Em produção/homologação liberada, o envio vai para o e-mail cadastrado na nota, não para e-mail de teste."]},
  {id:"whatsapp",title:"WhatsApp",category:"Comunicações",description:"Como abrir WhatsApp Web no número correto do responsável.",icon:MessageCircle,destination:"Enviar notas",steps:["Cadastre os WhatsApps da escola em Configurações → Integrações.","No envio, escolha qual número da escola será usado.","Confira se o responsável tem telefone com DDD e prefixo +55.","Clique em Preparar WhatsApp e envie manualmente no WhatsApp Web/app.","Depois confirme no JPI Fiscal se enviou ou cancele para gerar nova tentativa."],notes:["Se o WhatsApp disser que o número não existe, corrija o telefone no cadastro do responsável e gere nova tentativa."]},
  {id:"agenda-edu",title:"Agenda Edu",category:"Comunicações",description:"Mensagem manual com link seguro da nota.",icon:MessageCircle,destination:"Enviar notas",steps:["Confira se a integração Agenda Edu está disponível em Configurações.","Garanta que o aluno tenha ID/vínculo da Agenda Edu no cadastro.","Gere a mensagem pelo canal Agenda Edu.","Clique em Copiar mensagem e cole no canal escolhido da Agenda Edu.","Confira se o link da nota aparece em azul e abre PDF/XML."],notes:["A API pública não confirma leitura; o JPI Fiscal registra envio/preparo e histórico da tentativa."]},
  {id:"permissoes",title:"Usuários e permissões",category:"Segurança",description:"Controle do que cada usuário pode acessar ou executar.",icon:KeyRound,destination:"Configurações",steps:["O Master deve abrir Configurações → Usuários e Permissões.","Escolha o perfil do usuário: Administrador, Financeiro, Secretaria ou Consulta.","Libere somente os módulos necessários para a função.","Bloqueie usuários que não devem mais acessar.","Revise permissões antes da emissão fiscal real."],notes:["O perfil Master mantém acesso total e deve ser usado com cuidado."]},
  {id:"erros",title:"Erros mais comuns",category:"Suporte",description:"O que fazer quando algo não carrega, não salva ou a SEFIN rejeita.",icon:ShieldCheck,steps:["Clique em Atualizar após publicação ou correção de cadastro.","Se não salvar, confira campos obrigatórios em vermelho e mensagem no topo.","Se a SEFIN rejeitar, leia o código do erro e corrija cadastro, endereço, CPF/CNPJ ou DPS.","Se a nota foi cancelada, emita uma nova antes de enviar ao responsável.","Se o WhatsApp ou Agenda Edu não abrir, corrija cadastro do responsável/aluno e gere nova tentativa.","Se persistir, envie imagem com módulo, aluno, competência e horário."],notes:["Não repita envio fiscal enquanto a barra de progresso estiver ativa."]}
];

const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();

export function HelpPage({onNavigate}:{onNavigate:(page:Destination)=>void}){
  const [query,setQuery]=useState("");
  const [category,setCategory]=useState("Todos");
  const categories=["Todos",...Array.from(new Set(guides.map(guide=>guide.category)))];
  const filtered=useMemo(()=>guides.filter(guide=>{
    const categoryMatch=category==="Todos"||guide.category===category;
    const search=normalize(query.trim());
    return categoryMatch&&(!search||normalize([guide.title,guide.category,guide.description,...guide.steps,...(guide.notes||[])].join(" ")).includes(search));
  }),[query,category]);
  return <div className="help-page">
    <div className="page-heading help-heading"><div><span className="eyebrow">CENTRAL DE AJUDA</span><h1>Ajuda por módulo do sistema</h1><p>Veja o que conferir e ajustar em cada parte do JPI Fiscal.</p></div><div className="help-heading-icon"><HelpCircle/></div></div>
    <section className="help-search-panel"><div className="help-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Busque por SWeduc, cadastro, NFS-e, cancelamento, e-mail…" aria-label="Buscar na Central de ajuda"/></div><div className="help-categories">{categories.map(item=><button key={item} className={category===item?"active":""} onClick={()=>setCategory(item)}>{item}</button>)}</div></section>
    <div className="help-summary"><BookOpen/><span><strong>{filtered.length}</strong> {filtered.length===1?"orientação encontrada":"orientações encontradas"}</span><small>Conteúdo organizado pelos módulos atuais</small></div>
    {filtered.length?<div className="help-guides">{filtered.map((guide,index)=>{const Icon=guide.icon;return <details className="help-guide" key={guide.id} open={!query&&category==="Todos"&&index===0}><summary><span className="help-guide-icon"><Icon/></span><span><small>{guide.category}</small><strong>{guide.title}</strong><p>{guide.description}</p></span><span className="help-expand">+</span></summary><div className="help-guide-body"><ol>{guide.steps.map(step=><li key={step}>{step}</li>)}</ol>{guide.notes?.map(note=><div className="help-note" key={note}><ShieldCheck/><span>{note}</span></div>)}{guide.destination&&<button className="secondary" onClick={()=>onNavigate(guide.destination!)}>Abrir {guide.destination}</button>}</div></details>})}</div>:<div className="empty-state"><HelpCircle/><strong>Nenhuma orientação encontrada</strong><p>Tente outra palavra ou selecione Todos.</p></div>}
    <div className="notice help-footer-notice"><ShieldCheck/><div><strong>Precisa de suporte?</strong><span>Informe o módulo, aluno, competência, horário e a mensagem exibida. Não envie senhas, certificado A1 ou tokens.</span></div></div>
  </div>;
}
