"use client";

import { useMemo, useState } from "react";
import { BookOpen, CheckCircle2, FileCheck2, GraduationCap, HelpCircle, KeyRound, Mail, MailCheck, MessageCircle, Search, Settings, ShieldCheck, UsersRound, WalletCards } from "lucide-react";

type Destination = "Painel"|"Alunos e Responsáveis"|"Mensalidades"|"NFS-e"|"Enviar notas"|"Configurações";
type Guide = {
  id:string;
  title:string;
  category:string;
  description:string;
  icon:typeof BookOpen;
  destination?:Destination;
  steps:string[];
  notes?:string[];
};

const guides:Guide[]=[
  {id:"inicio",title:"Primeiros passos",category:"Começando",description:"Ordem recomendada para preparar o JPI Fiscal.",icon:CheckCircle2,destination:"Painel",steps:["Cadastre os dados da empresa em Configurações.","Anexe o certificado digital A1 e guarde sua senha no cofre seguro.","Cadastre os usuários e escolha as permissões de cada pessoa.","Configure e teste os canais de e-mail e WhatsApp.","Cadastre responsáveis, alunos e mensalidades.","Faça a homologação antes de qualquer emissão fiscal real."],notes:["A emissão real permanece desativada enquanto o processo de homologação não estiver concluído."]},
  {id:"empresa",title:"Dados da empresa",category:"Configurações",description:"CNPJ, endereço, regime tributário, atividades e logotipo.",icon:Settings,destination:"Configurações",steps:["Acesse Configurações → Empresa.","Confira CNPJ, razão social, inscrição municipal e endereço.","Revise o regime tributário, PIS e COFINS com a contabilidade.","Cadastre as atividades e autorizações da escola.","Clique em Salvar alterações."],notes:["Dados fiscais incorretos podem provocar rejeição da DPS. Consulte a contabilidade antes de alterar tributos."]},
  {id:"certificado",title:"Certificado digital A1",category:"Configurações",description:"Como anexar, trocar e proteger o certificado.",icon:KeyRound,destination:"Configurações",steps:["Acesse Configurações → Certificado A1.","Selecione o arquivo .pfx ou .p12.","Informe a senha do certificado e confira os dados identificados.","Guarde a senha com segurança no cofre.","Observe o aviso de validade na barra superior."],notes:["Nunca envie o arquivo ou a senha por WhatsApp, e-mail ou chat.","A substituição preserva o histórico do certificado anterior."]},
  {id:"email",title:"Integração de e-mail",category:"Integrações",description:"Conecte a conta da Locaweb e envie um teste seguro.",icon:Mail,destination:"Configurações",steps:["Confirme que a conta nfse@jejoaopaulo.com.br está ativa no webmail da Locaweb.","Acesse Configurações → Integrações → Comunicações.","Em Provedor de envio, selecione E-mail Locaweb.","Confira o servidor email-ssl.com.br, porta 465 e SSL/TLS.","Use nfse@jejoaopaulo.com.br como remetente e usuário SMTP.","Digite a senha da caixa diretamente no campo protegido.","Salve e envie um e-mail de teste."],notes:["A senha fica criptografada no cofre e não será exibida novamente.","Se a senha for alterada na Locaweb, atualize-a também no JPI Fiscal.","O endereço usado como Responder para precisa possuir uma caixa de entrada ativa."]},
  {id:"whatsapp",title:"Integração com WhatsApp",category:"Integrações",description:"Configure a Meta Cloud API e valide o número.",icon:MessageCircle,destination:"Configurações",steps:["Crie um aplicativo Business no Meta for Developers e adicione o produto WhatsApp.","Cadastre e confirme o número remetente.","Copie o Phone Number ID e o WhatsApp Business Account ID.","Crie um usuário do sistema e gere um token permanente com as permissões do WhatsApp.","Crie o modelo envio_nfse na categoria Utilidade, idioma Português (Brasil), com cabeçalho do tipo Documento.","No corpo do modelo, use nesta ordem: nome do responsável, nome do aluno, competência e link do XML.","Aguarde a aprovação do modelo pela Meta.","Acesse Configurações → Integrações → Comunicações e informe também um número interno para homologação.","Salve e teste a conexão. Esse teste apenas valida a conta e não envia mensagem.","Em Enviar notas → WhatsApp, faça o primeiro envio somente para o número interno configurado."],notes:["Na homologação, nenhuma mensagem é enviada ao número real do responsável.","O PDF segue anexado à mensagem. Como a Meta não aceita XML como anexo nativo, o XML fica disponível em um link privado válido por 7 dias.","Recomendamos um número exclusivo para o JPI Fiscal.","Nunca compartilhe o token da Meta fora da tela protegida do sistema."]},
  {id:"agenda-edu",title:"Integração com Agenda Edu",category:"Integrações",description:"Configure Mensagens com os responsáveis no Sandbox antes de liberar envios.",icon:MessageCircle,destination:"Configurações",steps:["Solicite à Agenda Edu o client_id, client_secret e x-school-token da escola com acesso à API v2.","Em Configurações → Integrações → Comunicações, abra Agenda Edu.","Informe as três credenciais diretamente nos campos protegidos. Nunca envie esses dados pelo chat.","Salve e clique em Testar conexão sem enviar mensagem. O sistema gerará um token OAuth 2.0 temporário e consultará os canais no Sandbox.","Informe o ID do canal somente de leitura que inclui as turmas dos alunos.","Associe cada aluno pelo ID da Agenda Edu ou pelo identificador externo cadastrado.","Em Enviar notas → Agenda Edu, teste uma NFS-e no Sandbox antes de habilitar os responsáveis reais."],notes:["A API usa OAuth 2.0 Client Credentials; o token temporário expira em duas horas e é renovado pelo servidor.","Cada mensagem de família é ligada a um único aluno e alcança os responsáveis vinculados a ele.","A API aceita um anexo por mensagem; por isso o PDF e o XML seguem em duas mensagens consecutivas.","A API pública de Mensagens não documenta confirmação de leitura. O JPI Fiscal registra envio aceito ou erro, sem inventar o estado lido.","Cada nota será entregue individualmente aos responsáveis do respectivo aluno, mesmo quando o usuário iniciar um lote."]},
  {id:"alunos",title:"Alunos e responsáveis",category:"Cadastros",description:"Cadastre uma vez e reaproveite o responsável pelo CPF.",icon:GraduationCap,destination:"Alunos e Responsáveis",steps:["Acesse Alunos e Responsáveis e clique em Novo aluno.","Digite primeiro o CPF ou CNPJ do responsável.","Se ele já estiver cadastrado, confira os dados encontrados e confirme o reaproveitamento.","Se for novo, preencha nome, contato e endereço.","Complete os dados do aluno e salve."],notes:["Confirme o CPF e o e-mail, pois eles serão usados nos documentos fiscais e nas entregas."]},
  {id:"mensalidades",title:"Mensalidades",category:"Financeiro",description:"Criação, competência, valor e situação do pagamento.",icon:WalletCards,destination:"Mensalidades",steps:["Acesse Mensalidades e clique em Nova mensalidade.","Selecione o aluno e informe competência, vencimento e valor.","Revise os dados antes de salvar.","Atualize a situação quando o pagamento for identificado.","Use os filtros para localizar mensalidades por período e situação."],notes:["A competência fiscal não pode ser posterior ao mês atual durante a homologação."]},
  {id:"nfse",title:"Emitir NFS-e em homologação",category:"NFS-e",description:"Valide, transmita e acompanhe o resultado com segurança.",icon:FileCheck2,destination:"NFS-e",steps:["Confira na barra superior se a SEFIN está disponível.","Localize a mensalidade e abra Ver DPS.","Revise tomador, serviço, competência, valor e tributos.","Confirme o envio apenas uma vez e acompanhe a barra de progresso.","Aguarde a mensagem de conclusão ou erro.","Quando houver rejeição, corrija os dados e use Corrigir para reenviar."],notes:["O botão fica bloqueado durante a transmissão para evitar envio duplicado.","O sistema preserva os XMLs e o histórico de cada tentativa."]},
  {id:"lote",title:"Enviar várias homologações",category:"NFS-e",description:"Selecione mensalidades e acompanhe a fila individual.",icon:FileCheck2,destination:"NFS-e",steps:["Na tela de NFS-e, filtre o período desejado.","Marque as mensalidades que serão homologadas.","Revise a quantidade e o valor total selecionado.","Inicie o envio em lote e acompanhe cada item da fila.","Se algum item falhar, repita somente os pendentes."],notes:["Cada nota é transmitida individualmente, mesmo quando iniciada em lote."]},
  {id:"entregas",title:"Enviar notas aos responsáveis",category:"Comunicações",description:"Escolha e-mail, WhatsApp ou Agenda Edu e acompanhe cada envio.",icon:MailCheck,destination:"Enviar notas",steps:["Acesse Enviar notas no menu principal.","Escolha Enviar por e-mail, WhatsApp ou Agenda Edu.","Use a busca e os filtros de situação e competência para localizar as notas.","Escolha a ordenação por data, aluno, valor ou quantidade de envios.","Selecione uma ou várias NFS-e ativas e acompanhe os resultados.","Nas notas enviadas, abra Documentos e histórico para visualizar ou baixar separadamente o PDF e o XML.","Para enviar novamente uma nota concluída, use o botão de reenvio do canal selecionado e confirme. O contador e a data do último envio serão atualizados."],notes:["A tela mostra até 20 notas por página para manter a visualização rápida no celular e no computador.","Durante a homologação, os e-mails são direcionados somente para administracao@jejoaopaulo.com.br e o WhatsApp somente para o número interno configurado.","Cada e-mail de homologação inclui o DANFSe em PDF e o XML da mesma versão da nota.","No WhatsApp, o DANFSe segue em PDF e o XML por link privado temporário.","Na Agenda Edu, o PDF e o XML seguem em duas Mensagens com os responsáveis vinculadas ao respectivo aluno.","Cada canal possui sua própria lista de pendentes, enviadas, erros e histórico.","Cada reenvio cria uma nova tentativa no histórico e não apaga os registros anteriores.","Os documentos permanecem privados e exigem uma sessão autorizada para visualização ou download.","Agenda Edu só será liberado depois da documentação, configuração e testes específicos desse canal."]},
  {id:"ajustes-nfse",title:"Cancelar, corrigir ou substituir",category:"NFS-e",description:"Escolha a ação correta para uma nota já processada.",icon:FileCheck2,destination:"NFS-e",steps:["Abra a área de notas emitidas e localize a NFS-e.","Para cancelamento, informe uma justificativa clara e confirme o evento.","Quando a correção exigir nova nota, use o fluxo de substituição.","Acompanhe a barra de progresso e aguarde a confirmação oficial.","Consulte o histórico para visualizar a versão ativa e os eventos anteriores."],notes:["Nem toda alteração é permitida após a autorização. O sistema indicará quando cancelar ou substituir."]},
  {id:"usuarios",title:"Usuários e permissões",category:"Segurança",description:"Convide pessoas e limite o acesso conforme a função.",icon:UsersRound,destination:"Configurações",steps:["Acesse Configurações → Usuários e Permissões.","Clique em Convidar usuário e informe nome, e-mail e perfil.","Escolha Administrador, Financeiro, Secretaria ou Consulta.","Revise periodicamente os acessos ativos.","Bloqueie imediatamente usuários que não devem mais acessar o sistema."],notes:["Somente Administradores podem alterar configurações, credenciais e permissões."]},
  {id:"seguranca",title:"Segurança e solução de problemas",category:"Segurança",description:"Cuidados com credenciais, servidor e mensagens de erro.",icon:ShieldCheck,steps:["Nunca compartilhe senha do A1, chave do Resend ou token da Meta.","Se a SEFIN estiver instável, aguarde o indicador ficar disponível antes de transmitir.","Em caso de sessão expirada, saia e entre novamente.","Leia a mensagem completa de rejeição antes de corrigir dados.","Não repita uma transmissão enquanto a barra de progresso estiver ativa.","Se o erro continuar, registre horário, aluno, competência e uma imagem da mensagem."],notes:["Os testes de conexão não emitem NFS-e e o teste do WhatsApp não envia mensagem."]}
];

const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();

export function HelpPage({onNavigate}:{onNavigate:(page:Destination)=>void}){
  const [query,setQuery]=useState("");
  const [category,setCategory]=useState("Todos");
  const categories=["Todos",...Array.from(new Set(guides.map(guide=>guide.category)))];
  const filtered=useMemo(()=>guides.filter(guide=>{
    const categoryMatch=category==="Todos"||guide.category===category;
    const search=normalize(query.trim());
    return categoryMatch&&(!search||normalize([guide.title,guide.category,guide.description,...guide.steps,...(guide.notes||[])].join(" ")).includes(search));
  }),[query,category]);
  return <div className="help-page">
    <div className="page-heading help-heading"><div><span className="eyebrow">CENTRAL DE AJUDA</span><h1>Como podemos ajudar?</h1><p>Orientações para configurar e utilizar os módulos do JPI Fiscal com segurança.</p></div><div className="help-heading-icon"><HelpCircle/></div></div>
    <section className="help-search-panel"><div className="help-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Busque por e-mail, WhatsApp, certificado, mensalidade…" aria-label="Buscar na Central de ajuda"/></div><div className="help-categories">{categories.map(item=><button key={item} className={category===item?"active":""} onClick={()=>setCategory(item)}>{item}</button>)}</div></section>
    <div className="help-summary"><BookOpen/><span><strong>{filtered.length}</strong> {filtered.length===1?"orientação encontrada":"orientações encontradas"}</span><small>Conteúdo disponível para todos os usuários</small></div>
    {filtered.length?<div className="help-guides">{filtered.map((guide,index)=>{const Icon=guide.icon;return <details className="help-guide" key={guide.id} open={!query&&category==="Todos"&&index===0}><summary><span className="help-guide-icon"><Icon/></span><span><small>{guide.category}</small><strong>{guide.title}</strong><p>{guide.description}</p></span><span className="help-expand">+</span></summary><div className="help-guide-body"><ol>{guide.steps.map(step=><li key={step}>{step}</li>)}</ol>{guide.notes?.map(note=><div className="help-note" key={note}><ShieldCheck/><span>{note}</span></div>)}{guide.destination&&<button className="secondary" onClick={()=>onNavigate(guide.destination!)}>Abrir {guide.destination}</button>}</div></details>})}</div>:<div className="empty-state"><HelpCircle/><strong>Nenhuma orientação encontrada</strong><p>Tente outra palavra ou selecione Todos.</p></div>}
    <div className="notice help-footer-notice"><ShieldCheck/><div><strong>Ainda ficou com dúvida?</strong><span>Não envie senhas ou tokens. Informe o módulo, o horário e a mensagem apresentada na tela.</span></div></div>
  </div>;
}
