"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Check, CircleDollarSign, Clock3, FileCheck2, Filter, MoreHorizontal, Plus, Search, ShieldCheck, UsersRound, WalletCards, X } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase";
import type { Role } from "./app-shell";

type Student = { id:number; nome:string; turma:string|null; segmento:string; responsavel:string; cpf_cnpj:string|null; email:string|null; whatsapp:string|null; endereco:string|null };
type Payment = { id:number; aluno_id:number; competencia:string; valor_mensalidade:number; valor_nfse:number; status_pagamento:string; status_nfse:string; numero_nfse:string|null; alunos:{nome:string;responsavel:string}|null };
const segments=["Maternal","Jardim de Infância","Pré-escola","1º ao 5º anos","6º ao 9º anos"];
const money=(value:number)=>Number(value).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

function Heading({title,desc,action}:{title:string;desc:string;action?:React.ReactNode}) { return <div className="page-heading"><div><h1>{title}</h1><p>{desc}</p></div>{action}</div> }
function Status({children}:{children:string}) { return <span className={`status ${children.toLowerCase()}`}>{children}</span> }
function Empty({children}:{children:string}) { return <div className="empty-state"><strong>Nenhum registro encontrado</strong><p>{children}</p></div> }
function ErrorBox({message}:{message:string}) { return message?<div className="error-box page-error">{message}</div>:null }

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) { return <div className="modal-backdrop"><div className="modal-card"><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose}><X/></button></div>{children}</div></div> }

export function LiveDashboard() {
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const [students,setStudents]=useState(0);const [payments,setPayments]=useState<Payment[]>([]);const [error,setError]=useState("");
 useEffect(()=>{if(!supabase)return;Promise.all([supabase.from("alunos").select("id",{count:"exact",head:true}),supabase.from("mensalidades").select("*, alunos(nome,responsavel)")]).then(([a,p])=>{if(a.error||p.error)setError(a.error?.message||p.error?.message||"");else{setStudents(a.count||0);setPayments((p.data??[]) as unknown as Payment[])}})},[supabase]);
 const paid=payments.filter(p=>p.status_pagamento==="Pago").reduce((sum,p)=>sum+Number(p.valor_mensalidade),0);const pending=payments.filter(p=>p.status_pagamento==="Aberto");const prepared=payments.filter(p=>p.status_nfse!=="Pendente").length;
 return <><Heading title="Painel" desc="Visão geral dos dados reais da operação escolar e fiscal."/><div className="notice warning"><ShieldCheck/><div><strong>Ambiente fiscal protegido</strong><span>A emissão real permanece desativada até a homologação.</span></div></div><ErrorBox message={error}/><section className="stat-grid"><article className="stat-card"><span className="stat-icon blue"><UsersRound/></span><div><span>Alunos cadastrados</span><strong>{students}</strong><small>Dados do Supabase</small></div></article><article className="stat-card"><span className="stat-icon green"><CircleDollarSign/></span><div><span>Mensalidades pagas</span><strong>{money(paid)}</strong><small>{payments.filter(p=>p.status_pagamento==="Pago").length} pagamentos</small></div></article><article className="stat-card"><span className="stat-icon amber"><Clock3/></span><div><span>Mensalidades em aberto</span><strong>{pending.length}</strong><small>{money(pending.reduce((s,p)=>s+Number(p.valor_mensalidade),0))} a receber</small></div></article><article className="stat-card"><span className="stat-icon purple"><FileCheck2/></span><div><span>Notas revisadas</span><strong>{prepared}</strong><small>{payments.length} mensalidades no total</small></div></article></section>{students===0&&payments.length===0&&<div style={{marginTop:16}}><Empty>Comece cadastrando o primeiro aluno no menu “Alunos e Responsáveis”.</Empty></div>}</>
}

export function LiveStudents({role}:{role:Role}) {
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]); const [items,setItems]=useState<Student[]>([]); const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const load=useCallback(async()=>{if(!supabase)return;setError("");const {data,error}=await supabase.from("alunos").select("*").order("nome");if(error)setError(error.message);else setItems(data??[])},[supabase]);
 useEffect(()=>{load()},[load]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setError("");const f=new FormData(e.currentTarget);const payload={nome:f.get("nome"),turma:f.get("turma")||null,segmento:f.get("segmento"),responsavel:f.get("responsavel"),cpf_cnpj:f.get("cpf_cnpj")||null,email:f.get("email")||null,whatsapp:f.get("whatsapp")||null,endereco:f.get("endereco")||null};const {error}=await supabase.from("alunos").insert(payload);setBusy(false);if(error){setError(error.message);return}setOpen(false);await load()}
 const filtered=items.filter(i=>(i.nome+i.responsavel).toLowerCase().includes(query.toLowerCase()));
 return <><Heading title="Alunos e Responsáveis" desc="Cadastros reais armazenados com segurança no Supabase." action={role!=="Consulta"?<button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/>Novo aluno</button>:undefined}/><ErrorBox message={error}/><div className="toolbar"><div className="search-input"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por aluno ou responsável"/></div><button className="secondary"><Filter size={17}/>Filtros</button></div>{filtered.length===0?<Empty>Use “Novo aluno” para realizar o primeiro cadastro.</Empty>:<div className="table-card"><table><thead><tr><th>Aluno</th><th>Turma</th><th>Segmento</th><th>Responsável</th><th>Contato</th><th></th></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><strong>{s.nome}</strong></td><td>{s.turma||"—"}</td><td>{s.segmento}</td><td>{s.responsavel}<span className="subcell">{s.cpf_cnpj||"CPF não informado"}</span></td><td>{s.whatsapp||s.email||"—"}</td><td><button className="icon-button"><MoreHorizontal/></button></td></tr>)}</tbody></table></div>}{open&&<Modal title="Cadastrar aluno e responsável" onClose={()=>setOpen(false)}><form className="data-form" onSubmit={create}><label>Nome do aluno<input name="nome" required/></label><div className="form-row"><label>Turma<input name="turma"/></label><label>Segmento<select name="segmento" required>{segments.map(s=><option key={s}>{s}</option>)}</select></label></div><label>Responsável financeiro<input name="responsavel" required/></label><div className="form-row"><label>CPF/CNPJ<input name="cpf_cnpj"/></label><label>WhatsApp<input name="whatsapp"/></label></div><label>E-mail<input name="email" type="email"/></label><label>Endereço<input name="endereco"/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary" disabled={busy}>{busy?"Salvando…":"Salvar cadastro"}</button></div></form></Modal>}</>
}

export function LivePayments({role}:{role:Role}) {
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]); const [items,setItems]=useState<Payment[]>([]);const [students,setStudents]=useState<Student[]>([]);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const load=useCallback(async()=>{if(!supabase)return;setError("");const [p,s]=await Promise.all([supabase.from("mensalidades").select("*, alunos(nome,responsavel)").order("created_at",{ascending:false}),supabase.from("alunos").select("*").order("nome")]);if(p.error)setError(p.error.message);else setItems((p.data??[]) as unknown as Payment[]);if(!s.error)setStudents(s.data??[])},[supabase]);useEffect(()=>{load()},[load]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);const f=new FormData(e.currentTarget);const value=Number(String(f.get("valor")).replace(",","."));const payload={aluno_id:Number(f.get("aluno_id")),competencia:f.get("competencia"),valor_mensalidade:value,valor_nfse:value,status_pagamento:f.get("status_pagamento")};const {error}=await supabase.from("mensalidades").insert(payload);setBusy(false);if(error){setError(error.message);return}setOpen(false);await load()}
 return <><Heading title="Mensalidades" desc="Cobranças reais; o valor inicial da NFS-e é copiado automaticamente." action={role==="Administrador"||role==="Financeiro"?<button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/>Nova cobrança</button>:undefined}/><ErrorBox message={error}/>{items.length===0?<Empty>Cadastre um aluno e depois registre sua primeira mensalidade.</Empty>:<div className="table-card"><table><thead><tr><th>Aluno</th><th>Competência</th><th>Mensalidade</th><th>Valor NFS-e</th><th>Pagamento</th><th>NFS-e</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td><strong>{p.alunos?.nome||`Aluno #${p.aluno_id}`}</strong></td><td>{p.competencia}</td><td>{money(p.valor_mensalidade)}</td><td>{money(p.valor_nfse)}</td><td><Status>{p.status_pagamento}</Status></td><td><Status>{p.status_nfse}</Status></td></tr>)}</tbody></table></div>}{open&&<Modal title="Registrar mensalidade" onClose={()=>setOpen(false)}><form className="data-form" onSubmit={create}><label>Aluno<select name="aluno_id" required><option value="">Selecione</option>{students.map(s=><option value={s.id} key={s.id}>{s.nome}</option>)}</select></label><div className="form-row"><label>Competência<input name="competencia" placeholder="08/2026" required/></label><label>Valor<input name="valor" type="number" min="0.01" step="0.01" required/></label></div><label>Status do pagamento<select name="status_pagamento"><option>Aberto</option><option>Pago</option></select></label><div className="notice compact"><WalletCards/><span>O valor da NFS-e será preenchido com o valor da mensalidade e poderá ser editado depois.</span></div><div className="form-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary" disabled={busy||students.length===0}>{busy?"Salvando…":"Salvar mensalidade"}</button></div></form></Modal>}</>
}

export function LiveInvoices({role}:{role:Role}) {
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const [items,setItems]=useState<Payment[]>([]);const [editing,setEditing]=useState<number|null>(null);const [value,setValue]=useState("");const [error,setError]=useState("");
 const load=useCallback(async()=>{if(!supabase)return;const {data,error}=await supabase.from("mensalidades").select("*, alunos(nome,responsavel)").order("created_at",{ascending:false});if(error)setError(error.message);else setItems((data??[]) as unknown as Payment[])},[supabase]);useEffect(()=>{load()},[load]);
 async function save(p:Payment){if(!supabase)return;const next=Number(value.replace(",","."));if(!next||next<=0){setError("Informe um valor válido.");return}const {error}=await supabase.from("mensalidades").update({valor_nfse:next,status_nfse:"Revisada"}).eq("id",p.id);if(error){setError(error.message);return}await supabase.from("historico_nfse").insert({mensalidade_id:p.id,evento:"valor_nfse_alterado",valor_anterior:p.valor_nfse,valor_novo:next,detalhes:"Alteração manual antes da emissão"});setEditing(null);await load()}
 return <><Heading title="NFS-e" desc="Preparação e revisão das notas, sem transmissão à prefeitura."/><div className="notice warning"><ShieldCheck/><div><strong>Emissão fiscal real bloqueada até homologação</strong><span>Os valores podem ser revisados; nenhuma nota será emitida.</span></div></div><ErrorBox message={error}/>{items.length===0?<Empty>As notas aparecerão automaticamente quando houver mensalidades cadastradas.</Empty>:<div className="table-card"><table><thead><tr><th>Aluno / Tomador</th><th>Competência</th><th>Origem</th><th>Valor NFS-e</th><th>Situação</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td><strong>{p.alunos?.nome||`Aluno #${p.aluno_id}`}</strong><span className="subcell">{p.alunos?.responsavel||"Responsável cadastrado"}</span></td><td>{p.competencia}</td><td><span className="auto-tag"><WalletCards size={14}/>Mensalidade</span></td><td>{editing===p.id?<div className="inline-edit"><span>R$</span><input autoFocus value={value} onChange={e=>setValue(e.target.value)}/><button onClick={()=>save(p)}><Check/></button></div>:<button className="editable-value" disabled={role==="Consulta"||role==="Secretaria"} onClick={()=>{setEditing(p.id);setValue(String(p.valor_nfse).replace(".",","))}}>{money(p.valor_nfse)} <small>editar</small></button>}</td><td><Status>{p.status_nfse}</Status></td></tr>)}</tbody></table></div>}</>
}
