"use client";
import { useState } from "react";
import { AlertCircle, ArrowUpRight, Building2, Check, CircleDollarSign, Clock3, FileCheck2, FilePlus2, Filter, Link2, MoreHorizontal, Plus, Search, ShieldCheck, SlidersHorizontal, UserCog, UsersRound, WalletCards } from "lucide-react";
import type { Role } from "./app-shell";

const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const students=[
 {name:"Alice Ferreira Lima",class:"Infantil 5",guardian:"Mariana Ferreira",phone:"(21) 99854-1203",status:"Ativo"},
 {name:"Bernardo Santos",class:"2º ano",guardian:"Carlos Eduardo Santos",phone:"(21) 99221-5578",status:"Ativo"},
 {name:"Clara Menezes Alves",class:"4º ano",guardian:"Renata Menezes",phone:"(21) 98773-8041",status:"Ativo"},
 {name:"Davi Oliveira Costa",class:"1º ano",guardian:"Patrícia Oliveira",phone:"(21) 99618-4420",status:"Pendente"}
];
const payments=[
 {student:"Alice Ferreira Lima",due:"10/08/2026",value:850,status:"Pago"},
 {student:"Bernardo Santos",due:"10/08/2026",value:920,status:"Pendente"},
 {student:"Clara Menezes Alves",due:"10/08/2026",value:920,status:"Pago"},
 {student:"Davi Oliveira Costa",due:"10/08/2026",value:850,status:"Atrasado"}
];
function Heading({title,desc,action}:{title:string;desc:string;action?:React.ReactNode}){return <div className="page-heading"><div><h1>{title}</h1><p>{desc}</p></div>{action}</div>}
function Status({children}:{children:string}){return <span className={`status ${children.toLowerCase()}`}>{children}</span>}
export function Dashboard(){return <><Heading title="Painel" desc="Visão geral da operação escolar e fiscal." action={<button className="primary"><FilePlus2 size={18}/>Nova NFS-e</button>}/><div className="notice warning"><ShieldCheck/><div><strong>Ambiente de homologação</strong><span>A emissão fiscal real está desativada. Você pode preparar e revisar notas com segurança.</span></div></div><section className="stat-grid">
 <article className="stat-card"><span className="stat-icon blue"><UsersRound/></span><div><span>Alunos ativos</span><strong>148</strong><small><ArrowUpRight/> 6 novos este mês</small></div></article>
 <article className="stat-card"><span className="stat-icon green"><CircleDollarSign/></span><div><span>Recebido no mês</span><strong>R$ 112.640</strong><small><ArrowUpRight/> 92% das mensalidades</small></div></article>
 <article className="stat-card"><span className="stat-icon amber"><Clock3/></span><div><span>Mensalidades pendentes</span><strong>12</strong><small>R$ 10.780 a receber</small></div></article>
 <article className="stat-card"><span className="stat-icon purple"><FileCheck2/></span><div><span>Notas preparadas</span><strong>136</strong><small>12 aguardando revisão</small></div></article></section>
 <section className="two-col"><article className="panel"><div className="panel-title"><div><h2>Mensalidades recentes</h2><p>Acompanhe os últimos pagamentos.</p></div><button className="text-button">Ver todas</button></div><div className="activity-list">{payments.slice(0,3).map((p,i)=><div className="activity" key={p.student}><div className="avatar soft">{p.student[0]}</div><div><strong>{p.student}</strong><span>Vencimento {p.due}</span></div><b>{money(p.value)}</b><Status>{p.status}</Status></div>)}</div></article>
 <article className="panel"><div className="panel-title"><div><h2>Resumo fiscal</h2><p>Competência agosto de 2026.</p></div></div><div className="progress-item"><div><span>Notas preparadas</span><b>136 de 148</b></div><progress value="136" max="148"/></div><div className="fiscal-total"><span>Valor total preparado</span><strong>R$ 116.730,00</strong></div><div className="notice compact"><AlertCircle/><span>12 notas precisam ser revisadas antes da homologação.</span></div></article></section></>}

export function Students({role}:{role:Role}){const [q,setQ]=useState("");const list=students.filter(s=>(s.name+s.guardian).toLowerCase().includes(q.toLowerCase()));return <><Heading title="Alunos e Responsáveis" desc="Cadastros acadêmicos, responsáveis financeiros e contatos." action={role!=="Consulta"?<button className="primary"><Plus size={18}/>Novo aluno</button>:undefined}/><div className="toolbar"><div className="search-input"><Search/><input placeholder="Buscar por aluno ou responsável" value={q} onChange={e=>setQ(e.target.value)}/></div><button className="secondary"><Filter size={17}/>Filtros</button></div><div className="table-card"><table><thead><tr><th>Aluno</th><th>Turma</th><th>Responsável</th><th>Contato</th><th>Situação</th><th></th></tr></thead><tbody>{list.map(s=><tr key={s.name}><td><div className="name-cell"><div className="avatar soft">{s.name[0]}</div><strong>{s.name}</strong></div></td><td>{s.class}</td><td>{s.guardian}</td><td>{s.phone}</td><td><Status>{s.status}</Status></td><td><button className="icon-button"><MoreHorizontal/></button></td></tr>)}</tbody></table></div></>}

export function Payments({role}:{role:Role}){return <><Heading title="Mensalidades" desc="Controle de cobranças e valores que alimentam a preparação das notas." action={role!=="Consulta"?<button className="primary"><Plus size={18}/>Nova cobrança</button>:undefined}/><div className="mini-stats"><div><span>Previsto no mês</span><strong>R$ 123.420,00</strong></div><div><span>Recebido</span><strong className="green-text">R$ 112.640,00</strong></div><div><span>Em aberto</span><strong className="amber-text">R$ 10.780,00</strong></div></div><div className="toolbar"><div className="search-input"><Search/><input placeholder="Buscar mensalidade"/></div><button className="secondary"><SlidersHorizontal size={17}/>Agosto de 2026</button></div><div className="table-card"><table><thead><tr><th>Aluno</th><th>Vencimento</th><th>Valor</th><th>Situação</th><th>NFS-e</th><th></th></tr></thead><tbody>{payments.map(p=><tr key={p.student}><td><strong>{p.student}</strong></td><td>{p.due}</td><td>{money(p.value)}</td><td><Status>{p.status}</Status></td><td><Status>{p.status==="Pago"?"Preparada":"Aguardando"}</Status></td><td><button className="icon-button"><MoreHorizontal/></button></td></tr>)}</tbody></table></div></>}

export function Invoices({role}:{role:Role}){const [editing,setEditing]=useState<string|null>(null);const [vals,setVals]=useState<Record<string,string>>({"Alice Ferreira Lima":"850,00","Clara Menezes Alves":"920,00"});return <><Heading title="NFS-e" desc="Prepare, revise e acompanhe as notas fiscais de serviço." action={role!=="Consulta"?<button className="primary"><FilePlus2 size={18}/>Preparar notas</button>:undefined}/><div className="notice warning"><ShieldCheck/><div><strong>Emissão real bloqueada até homologação</strong><span>Nenhum documento será enviado à prefeitura. Os valores abaixo podem ser revisados livremente.</span></div></div><div className="toolbar"><div className="search-input"><Search/><input placeholder="Buscar nota ou tomador"/></div><button className="secondary"><Filter size={17}/>Preparadas</button></div><div className="table-card"><table><thead><tr><th>Tomador / Aluno</th><th>Competência</th><th>Origem do valor</th><th>Valor da NFS-e</th><th>Situação</th><th></th></tr></thead><tbody>{payments.filter(p=>p.status==="Pago").map(p=><tr key={p.student}><td><strong>{p.student}</strong><span className="subcell">Responsável financeiro cadastrado</span></td><td>08/2026</td><td><span className="auto-tag"><WalletCards size={14}/>Mensalidade paga</span></td><td>{editing===p.student?<div className="inline-edit"><span>R$</span><input autoFocus value={vals[p.student]} onChange={e=>setVals({...vals,[p.student]:e.target.value})}/><button onClick={()=>setEditing(null)}><Check/></button></div>:<button className="editable-value" disabled={role==="Consulta"} onClick={()=>setEditing(p.student)}>{money(Number(vals[p.student].replace(".","").replace(",",".")))} <small>editar</small></button>}</td><td><Status>Preparada</Status></td><td><button className="icon-button"><MoreHorizontal/></button></td></tr>)}</tbody></table></div></>}

type Tab="Integrações"|"Usuários e Permissões";
export function SettingsPage(){const [tab,setTab]=useState<Tab>("Integrações");return <><Heading title="Configurações" desc="Gerencie conexões, acessos e regras do sistema."/><div className="tabs"><button className={tab==="Integrações"?"active":""} onClick={()=>setTab("Integrações")}><Link2/>Integrações</button><button className={tab==="Usuários e Permissões"?"active":""} onClick={()=>setTab("Usuários e Permissões")}><UserCog/>Usuários e Permissões</button></div>{tab==="Integrações"?<Integrations/>:<Permissions/>}</>}
function Integrations(){return <div className="settings-grid"><article className="integration-card"><div className="integration-head"><span className="integration-icon green"><Building2/></span><Status>Conectado</Status></div><h3>Supabase</h3><p>Banco de dados, autenticação e sessões do JPI Fiscal.</p><div className="integration-meta"><span>Ambiente atual</span><strong>Produção</strong></div><button className="secondary full">Ver configuração</button></article><article className="integration-card"><div className="integration-head"><span className="integration-icon blue"><FileCheck2/></span><Status>Homologação</Status></div><h3>Provedor de NFS-e</h3><p>Integração municipal preparada, sem envio fiscal real.</p><div className="integration-meta"><span>Emissão real</span><strong className="amber-text">Desativada</strong></div><button className="secondary full">Configurar homologação</button></article><article className="integration-card"><div className="integration-head"><span className="integration-icon purple"><Link2/></span><Status>Pendente</Status></div><h3>Comunicações</h3><p>Configure e-mail e WhatsApp para recibos e avisos.</p><div className="integration-meta"><span>Canal</span><strong>Não configurado</strong></div><button className="secondary full">Configurar canais</button></article></div>}
function Permissions(){const rows=[{name:"Administrador do sistema",email:"admin@jpi.edu.br",role:"Administrador"},{name:"Equipe Financeira",email:"financeiro@jpi.edu.br",role:"Financeiro"},{name:"Secretaria JPI",email:"secretaria@jpi.edu.br",role:"Secretaria"},{name:"Auditoria",email:"consulta@jpi.edu.br",role:"Consulta"}];return <><div className="permission-legend"><div><ShieldCheck/><div><strong>Controle por nível de acesso</strong><p>Administrador gerencia tudo; Financeiro opera cobranças e NFS-e; Secretaria cuida dos cadastros; Consulta apenas visualiza.</p></div></div><button className="primary"><Plus/>Convidar usuário</button></div><div className="table-card"><table><thead><tr><th>Usuário</th><th>Nível de acesso</th><th>Status</th><th>Último acesso</th><th></th></tr></thead><tbody>{rows.map((u,i)=><tr key={u.email}><td><div className="name-cell"><div className="avatar soft">{u.name[0]}</div><div><strong>{u.name}</strong><span className="subcell">{u.email}</span></div></div></td><td><span className="role-tag">{u.role}</span></td><td><Status>Ativo</Status></td><td>{i===0?"Agora":"18/08/2026"}</td><td><button className="icon-button"><MoreHorizontal/></button></td></tr>)}</tbody></table></div></>}
