"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Check,RefreshCw,Search,UsersRound} from "lucide-react";
import {createSupabaseBrowserClient} from "@/lib/supabase";
import {authenticatedFetch} from "@/lib/authenticated-fetch";

type AcademicYear={id:number;year:number};
type SweducStudent={matricula_id:number;nome:string;numero_matricula:string|null;status:string|null;unidade:string|null;curso:string|null;serie:string|null;turma:string|null;ano_letivo:string|null;responsaveis:Array<{nome?:string;telefones?:Array<{numero?:string}>;emails?:Array<{email?:string}>}>;financeiro:Array<{numero_titulo?:string;valor?:string;situacao?:string}>;detalhes_carregados?:boolean};

export function SweducOperationalPicker({onStudentReady}:{onStudentReady:(student:{id:number;nome:string})=>void}){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const [years,setYears]=useState<AcademicYear[]>([]);const [selectedYear,setSelectedYear]=useState<number|null>(null);const [students,setStudents]=useState<SweducStudent[]>([]);const [query,setQuery]=useState("");const [selected,setSelected]=useState<SweducStudent|null>(null);const [busy,setBusy]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");
  const token=useCallback(async()=>{if(!supabase)throw new Error("Sessão indisponível. Entre novamente.");const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Sua sessão expirou. Entre novamente.");return session.access_token},[supabase]);
  const loadYears=useCallback(async()=>{try{const accessToken=await token();const response=await authenticatedFetch("/api/integrations/sweduc",{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"});const data=await response.json().catch(()=>({})) as {academicYears?:AcademicYear[];selectedAcademicYear?:number;config?:{credencial_configurada:boolean};error?:string};if(!response.ok)throw new Error(data.error||"Não foi possível carregar os anos letivos da SWeduc.");setYears(data.academicYears||[]);setSelectedYear(data.selectedAcademicYear||data.academicYears?.[0]?.year||null);if(!data.config?.credencial_configurada)setMessage("A conexão SWeduc ainda precisa ser configurada pelo Master.")}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar a SWeduc.")}},[token]);
  useEffect(()=>{void loadYears()},[loadYears]);
  const visible=useMemo(()=>{const term=query.trim().toLocaleLowerCase("pt-BR");if(!term)return students;return students.filter(student=>[student.nome,student.numero_matricula,String(student.matricula_id),student.turma,student.serie,student.curso,student.responsaveis[0]?.nome].filter(Boolean).some(value=>String(value).toLocaleLowerCase("pt-BR").includes(term)))},[students,query]);
  async function consult(){if(!selectedYear)return;setBusy("consult");setError("");setMessage(`Consultando alunos de ${selectedYear} na SWeduc…`);setStudents([]);setSelected(null);let page=1;let total=0;try{const accessToken=await token();while(page<=1000){const response=await authenticatedFetch("/api/integrations/sweduc",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({action:"sync",page,academicYear:selectedYear}),cache:"no-store"});const data=await response.json().catch(()=>({})) as {students?:SweducStudent[];nextPage?:number|null;lastPage?:number;academicYear?:number;error?:string};if(!response.ok)throw new Error(data.error||"Não foi possível consultar a SWeduc.");const loaded=data.students||[];total+=loaded.length;setStudents(current=>[...current,...loaded]);setMessage(data.nextPage?`Carregando página ${page} de ${data.lastPage||"…"} · ${total} matrícula(s) na tela.`:`Consulta concluída: ${total} matrícula(s) na tela. Nada foi salvo ainda.`);if(!data.nextPage)break;page=data.nextPage}}catch(e){setError(e instanceof Error?e.message:"Não foi possível consultar a SWeduc.")}finally{setBusy("")}}
  async function loadForNote(student:SweducStudent){setBusy(`import-${student.matricula_id}`);setError("");setMessage("");try{const accessToken=await token();const response=await authenticatedFetch("/api/integrations/sweduc",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({action:"import",matriculaId:student.matricula_id,responsibleIndex:0,student}),cache:"no-store"});const data=await response.json().catch(()=>({})) as {student?:{id:number;nome:string};message?:string;error?:string};if(!response.ok||!data.student)throw new Error(data.error||"Não foi possível carregar este aluno para a nota.");setMessage(data.message||"Aluno carregado para a nota.");onStudentReady(data.student)}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar este aluno para a nota.")}finally{setBusy("")}}
  return <section className="notice compact sweduc-operational-picker"><UsersRound/><div><strong>Buscar aluno na SWeduc</strong><span>Escolha o ano letivo e carregue o aluno para a nota sem abrir Configurações. Nada é salvo até clicar em Carregar para a nota.</span><div className="toolbar sweduc-year-toolbar"><label>Ano letivo<select value={selectedYear||""} onChange={event=>{setSelectedYear(Number(event.target.value));setStudents([]);setSelected(null);setQuery("")}}>{years.map(year=><option key={year.year} value={year.year}>{year.year}</option>)}</select></label><div className="search-input"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar aluno, matrícula, turma ou responsável"/></div><button type="button" className="secondary" disabled={Boolean(busy)||!selectedYear} onClick={()=>void consult()}><RefreshCw size={17}/>{busy==="consult"?"Consultando…":"Consultar SWeduc"}</button></div>{error&&<span className="agenda-secret-error">{error}</span>}{message&&<small>{message}</small>}{visible.length>0&&<div className="table-card"><table><thead><tr><th>Ano</th><th>Aluno</th><th>Matrícula</th><th>Turma / série</th><th>Responsável financeiro</th><th></th></tr></thead><tbody>{visible.slice(0,80).map(student=><tr key={student.matricula_id} className={selected?.matricula_id===student.matricula_id?"selected-row":""} onClick={()=>setSelected(student)}><td>{student.ano_letivo||selectedYear}</td><td><strong>{student.nome}</strong><span className="subcell">{student.unidade||"Unidade não informada"}</span></td><td>{student.numero_matricula||student.matricula_id}</td><td>{[student.turma,student.serie].filter(Boolean).join(" · ")||"—"}</td><td>{student.responsaveis[0]?.nome||"Não informado"}<span className="subcell">{student.responsaveis[0]?.telefones?.[0]?.numero||student.responsaveis[0]?.emails?.[0]?.email||"Sem contato"}</span></td><td><button type="button" className="primary mini" disabled={Boolean(busy)} onClick={event=>{event.stopPropagation();void loadForNote(student)}}>{busy===`import-${student.matricula_id}`?"Carregando…":<><Check size={15}/>Carregar para a nota</>}</button></td></tr>)}</tbody></table>{visible.length>80&&<small>Mostrando os 80 primeiros resultados. Use a busca para localizar o aluno.</small>}</div>}</div></section>;
}
