"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {BookOpenCheck,KeyRound,RefreshCw,Search,ShieldCheck,UsersRound} from "lucide-react";
import {authenticatedFetch} from "@/lib/authenticated-fetch";

type Config={host:string|null;credencial_configurada:boolean;ultimo_status:string;testada_em:string|null;sincronizada_em:string|null;ultimo_erro:string|null;total_sincronizado:number};
type Student={matricula_id:number;nome:string;numero_matricula:string|null;status:string|null;unidade:string|null;curso:string|null;serie:string|null;turma:string|null;ano_letivo:string|null;responsaveis:Array<{nome?:string;parentesco?:string;telefones?:Array<{numero?:string}>;emails?:Array<{email?:string}>}>;financeiro:Array<{numero_titulo?:string;valor?:string;situacao?:string}>};
export function SweducSettings({accessToken,canEdit,onStatus}:{accessToken:string|null;canEdit:boolean;onStatus?:(config:Config)=>void}){
  const [config,setConfig]=useState<Config|null>(null);const [students,setStudents]=useState<Student[]>([]);const [host,setHost]=useState("");const [clientId,setClientId]=useState("");const [clientSecret,setClientSecret]=useState("");const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [search,setSearch]=useState("");const [busy,setBusy]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");
  const load=useCallback(async(query="")=>{if(!accessToken)return;const response=await authenticatedFetch(`/api/integrations/sweduc${query?`?search=${encodeURIComponent(query)}`:""}`,{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"});const data=await response.json().catch(()=>({})) as {config?:Config;students?:Student[];error?:string};if(response.status===401)window.dispatchEvent(new Event("jpi-session-invalid"));if(!response.ok||!data.config)throw new Error(data.error||"Não foi possível carregar a SWeduc.");setConfig(data.config);setHost(current=>current||data.config?.host||"");setStudents(data.students||[]);onStatus?.(data.config)},[accessToken,onStatus]);
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"Não foi possível carregar a SWeduc."))},[load]);
  async function run(action:string,payload:Record<string,string|number>={}){if(!accessToken)throw new Error("Sessão expirada.");const response=await authenticatedFetch("/api/integrations/sweduc",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({action,...payload}),cache:"no-store"});const data=await response.json().catch(()=>({})) as {message?:string;error?:string;nextPage?:number|null;lastPage?:number;synced?:number};if(response.status===401)window.dispatchEvent(new Event("jpi-session-invalid"));if(!response.ok)throw new Error(data.error||"Não foi possível concluir a operação.");return data}
  async function act(name:string,fn:()=>Promise<{message?:string}>){setBusy(name);setError("");setMessage("");try{const result=await fn();setMessage(result.message||"Operação concluída.");await load();}catch(e){setError(e instanceof Error?e.message:"Não foi possível concluir a operação.")}finally{setBusy("")}}
  async function save(event:FormEvent){event.preventDefault();await act("save",()=>run("save",{host,clientId,clientSecret,username,password}));setClientId("");setClientSecret("");setUsername("");setPassword("")}
  async function syncAll(){setBusy("sync");setError("");setMessage("Iniciando sincronização…");let page=1;let totalSynced=0;try{while(page<=100){const result=await run("sync",{page});totalSynced+=Number(result.synced||0);setMessage(result.nextPage?`Sincronizando página ${page} de ${result.lastPage||"…"} · ${totalSynced} matrícula(s) atualizada(s).`:`Sincronização concluída: ${totalSynced} matrícula(s) importada(s) ou atualizada(s).`);if(!result.nextPage)break;page=result.nextPage}await load();}catch(e){setError(e instanceof Error?`${e.message} ${totalSynced?`${totalSynced} matrícula(s) já foram preservadas.`:""}`:"Não foi possível concluir a sincronização.")}finally{setBusy("")}}
  const tone=config?.ultimo_status==="conectado"?"connected":config?.ultimo_status==="erro"?"disconnected":"pending";const label=config?.ultimo_status==="conectado"?"Conectado":config?.ultimo_status==="erro"?"Erro":config?.credencial_configurada?"Pendente":"Não configurado";
  return <div className="integration-detail-panel"><div className="integration-detail-heading"><span className="integration-icon blue"><BookOpenCheck/></span><div><h2>SWeduc</h2><p>Alunos, matrículas, responsáveis e dados financeiros.</p></div><span className={`integration-state-badge ${tone}`}><i/>{label}</span></div>
    {error&&<div className="error-box">{error}</div>}{message&&<div className="success-box">{message}</div>}
    <div className="notice compact"><ShieldCheck/><span>Esta integração é independente da Agenda Edu. As credenciais ficam no cofre do servidor e nunca aparecem em logs ou no código.</span></div>
    <form className="communication-channel-card data-form" onSubmit={save}><div className="communication-channel-head"><span className="integration-icon blue"><KeyRound/></span><div><h3>Conexão segura</h3><small>OAuth 2 · API oficial de Alunos</small></div></div>
      <label>HOST<input type="url" value={host} onChange={e=>setHost(e.target.value)} placeholder="https://seu-host.sweduc.com.br" required disabled={!canEdit}/></label>
      <label>CLIENT_ID<input type="password" value={clientId} onChange={e=>setClientId(e.target.value)} placeholder={config?.credencial_configurada?"Protegido — deixe vazio para manter":"CLIENT_ID fornecido pela SWeduc"} autoComplete="new-password" disabled={!canEdit}/></label>
      <label>CLIENT_SECRET<input type="password" value={clientSecret} onChange={e=>setClientSecret(e.target.value)} placeholder={config?.credencial_configurada?"Protegido — deixe vazio para manter":"CLIENT_SECRET fornecido pela SWeduc"} autoComplete="new-password" disabled={!canEdit}/></label>
      <label>Usuário<input value={username} onChange={e=>setUsername(e.target.value)} placeholder={config?.credencial_configurada?"Protegido — deixe vazio para manter":"Usuário autorizado"} autoComplete="off" disabled={!canEdit}/></label>
      <label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={config?.credencial_configurada?"Protegida — deixe vazio para manter":"Senha do usuário"} autoComplete="new-password" disabled={!canEdit}/></label>
      {canEdit&&<div className="form-actions"><button className="primary" disabled={Boolean(busy)}>{busy==="save"?"Salvando…":"Salvar configuração"}</button><button type="button" className="secondary" disabled={Boolean(busy)||!config?.credencial_configurada} onClick={()=>void act("test",()=>run("test"))}>{busy==="test"?"Testando…":"Testar conexão"}</button><button type="button" className="secondary" disabled={Boolean(busy)||config?.ultimo_status!=="conectado"} onClick={()=>void syncAll()}><RefreshCw/>{busy==="sync"?"Sincronizando…":"Sincronizar alunos"}</button></div>}
      {(config?.testada_em||config?.sincronizada_em)&&<small className="last-test">{config.testada_em&&`Último teste: ${new Date(config.testada_em).toLocaleString("pt-BR")}`}{config.sincronizada_em&&` · Última sincronização: ${new Date(config.sincronizada_em).toLocaleString("pt-BR")}`}</small>}
    </form>
    <div className="communication-channel-card"><div className="communication-channel-head"><span className="integration-icon blue"><UsersRound/></span><div><h3>Alunos importados</h3><small>{config?.total_sincronizado||0} matrícula(s) na última sincronização</small></div></div><div className="toolbar"><div className="search-input"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar aluno por nome"/></div><button type="button" className="secondary" onClick={()=>void load(search).catch(e=>setError(e.message))}>Consultar</button></div>
      <div className="table-card"><table><thead><tr><th>Aluno</th><th>Matrícula</th><th>Turma / série</th><th>Responsáveis e contatos</th><th>Financeiro</th><th>Situação</th></tr></thead><tbody>{students.map(student=><tr key={student.matricula_id}><td><strong>{student.nome}</strong><span className="subcell">{student.unidade||"Unidade não informada"}</span></td><td>{student.numero_matricula||student.matricula_id}<span className="subcell">{student.ano_letivo||"—"}</span></td><td>{[student.turma,student.serie].filter(Boolean).join(" · ")||"—"}<span className="subcell">{student.curso||""}</span></td><td>{student.responsaveis[0]?.nome||"Não informado"}<span className="subcell">{student.responsaveis[0]?.telefones?.[0]?.numero||student.responsaveis[0]?.emails?.[0]?.email||"Sem contato"}</span></td><td>{student.financeiro.length?`${student.financeiro.length} título(s) disponível(is)`:"Sem dados"}</td><td><span className="status">{student.status||"Não informado"}</span></td></tr>)}{!students.length&&<tr><td colSpan={6}>Nenhum aluno sincronizado ou encontrado.</td></tr>}</tbody></table></div>
    </div>
  </div>;
}
