"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {ArrowUpRight,BookOpenCheck,Check,ChevronRight,Copy,Eye,EyeOff,KeyRound,Link2,RefreshCw,Search,ShieldCheck,UsersRound,X} from "lucide-react";
import {authenticatedFetch} from "@/lib/authenticated-fetch";
import type {AppPage} from "./app-shell";

type SweducGrant="client_credentials"|"password";
type Config={host:string|null;credencial_configurada:boolean;ultimo_status:string;testada_em:string|null;sincronizada_em:string|null;ultimo_erro:string|null;total_sincronizado:number;anos_sincronizacao:number[];auth_method:SweducGrant;usuario_configurado:boolean;ano_letivo_ativo:number;cofre_configurado:boolean};
type AcademicYear={id:number;year:number};
type Student={matricula_id:number;nome:string;numero_matricula:string|null;status:string|null;unidade:string|null;curso:string|null;serie:string|null;turma:string|null;ano_letivo:string|null;responsaveis:Array<{nome?:string;parentesco?:string;telefones?:Array<{numero?:string}>;emails?:Array<{email?:string}>}>;financeiro:Array<{numero_titulo?:string;valor?:string;situacao?:string}>;detalhes_carregados?:boolean};
type TemporaryTestResult={message:string;checks:{oauth:"confirmed";studentList:"confirmed";studentDetails:"confirmed"|"not_checked";grantType:"client_credentials"|"password";activeAcademicYear:number}};
export function SweducSettings({accessToken,canEdit,isMaster,onStatus,onNavigate}:{accessToken:string|null;canEdit:boolean;isMaster:boolean;onStatus?:(config:Config)=>void;onNavigate?:(page:AppPage)=>void}){
  const [config,setConfig]=useState<Config|null>(null);const [students,setStudents]=useState<Student[]>([]);const [host,setHost]=useState("");const [clientId,setClientId]=useState("");const [clientSecret,setClientSecret]=useState("");const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [search,setSearch]=useState("");const [busy,setBusy]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");
  const [apiInfoOpen,setApiInfoOpen]=useState(false);const [masterSecrets,setMasterSecrets]=useState<{grantType:SweducGrant;clientId:string;clientSecret:string;username:string;password:string}|null>(null);const [secretsVisible,setSecretsVisible]=useState(false);const [secretsBusy,setSecretsBusy]=useState(false);const [secretsError,setSecretsError]=useState("");const [copied,setCopied]=useState("");
  const [temporaryTest,setTemporaryTest]=useState<TemporaryTestResult|null>(null);const [academicYears,setAcademicYears]=useState<AcademicYear[]>([]);const [selectedYear,setSelectedYear]=useState<number|null>(null);const [selectedSyncYears,setSelectedSyncYears]=useState<number[]>([]);const [selectedMatriculaId,setSelectedMatriculaId]=useState<number|null>(null);const [selectedResponsibleIndex,setSelectedResponsibleIndex]=useState(0);
  const load=useCallback(async(query="",year?:number|null)=>{if(!accessToken)return;const params=new URLSearchParams();if(query.trim())params.set("search",query.trim());if(year)params.set("year",String(year));const response=await authenticatedFetch(`/api/integrations/sweduc${params.size?`?${params}`:""}`,{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"});const data=await response.json().catch(()=>({})) as {config?:Config;students?:Student[];academicYears?:AcademicYear[];syncYears?:number[];suggestedSyncYears?:number[];selectedAcademicYear?:number;error?:string};if(response.status===401)window.dispatchEvent(new Event("jpi-session-invalid"));if(!response.ok||!data.config)throw new Error(data.error||"Não foi possível carregar a SWeduc.");setConfig(data.config);setHost(current=>current||data.config?.host||"");setAcademicYears(data.academicYears||[]);setSelectedSyncYears((data.syncYears?.length?data.syncYears:data.suggestedSyncYears)||data.config.anos_sincronizacao||[]);setSelectedYear(data.selectedAcademicYear||data.config.ano_letivo_ativo);setStudents(data.students||[]);setSelectedMatriculaId(current=>current&&(data.students||[]).some(student=>student.matricula_id===current)?current:null);onStatus?.(data.config)},[accessToken,onStatus]);
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"Não foi possível carregar a SWeduc."))},[load]);
  useEffect(()=>{if(!masterSecrets)return;const timer=window.setTimeout(()=>{setMasterSecrets(null);setSecretsVisible(false);setCopied("")},60000);return()=>window.clearTimeout(timer)},[masterSecrets]);
  async function run(action:string,payload:Record<string,unknown>={}){if(!accessToken)throw new Error("Sessão expirada.");const response=await authenticatedFetch("/api/integrations/sweduc",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({action,...payload}),cache:"no-store"});const data=await response.json().catch(()=>({})) as {message?:string;error?:string;nextPage?:number|null;lastPage?:number;synced?:number;academicYear?:number;students?:Student[];totalAvailable?:number;student?:{id:number;nome:string}};if(response.status===401)window.dispatchEvent(new Event("jpi-session-invalid"));if(!response.ok)throw new Error(data.error||"Não foi possível concluir a operação.");return data}
  async function act(name:string,fn:()=>Promise<{message?:string}>){setBusy(name);setError("");setMessage("");try{const result=await fn();setMessage(result.message||"Operação concluída.");await load();return true}catch(e){setError(e instanceof Error?e.message:"Não foi possível concluir a operação.");return false}finally{setBusy("")}}
  async function save(event:FormEvent){event.preventDefault();const saved=await act("save",()=>run("save",{host,clientId,clientSecret,grantType:"password",username,password}));if(saved){setClientId("");setClientSecret("");setUsername("");setPassword("");setTemporaryTest(null)}}
  async function testUnsavedCredentials(){if(!isMaster||!accessToken)return;setBusy("temporary-test");setError("");setMessage("");setTemporaryTest(null);try{const response=await authenticatedFetch("/api/integrations/sweduc/test-credentials",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({host,clientId,clientSecret,useUsernamePassword:true,username,password}),cache:"no-store"});const data=await response.json().catch(()=>({})) as Partial<TemporaryTestResult>&{error?:string};if(response.status===401)window.dispatchEvent(new Event("jpi-session-invalid"));if(!response.ok||!data.message||!data.checks)throw new Error(data.error||"A SWeduc não confirmou estas credenciais.");setTemporaryTest({message:data.message,checks:data.checks})}catch(e){setError(e instanceof Error?e.message:"Não foi possível testar estas credenciais.")}finally{setBusy("")}}
  async function syncAll(){const year=selectedYear||config?.ano_letivo_ativo;setBusy("sync");setError("");setStudents([]);setSelectedMatriculaId(null);setMessage(`Consultando alunos do ano letivo ${year||"selecionado"} diretamente na SWeduc pela conexão salva…`);let page=1;let totalLoaded=0;try{while(page<=1000){const result=await run("sync",{page,academicYear:year||""});const loaded=result.students||[];totalLoaded+=loaded.length;setStudents(current=>[...current,...loaded]);const academicYear=result.academicYear||year||"selecionado";setMessage(result.nextPage?`Consultando página ${page} de ${result.lastPage||"…"} do ano letivo ${academicYear} · ${totalLoaded} matrícula(s) exibida(s) na tela. Nada foi salvo.`:`Consulta do ano letivo ${academicYear} concluída: ${totalLoaded} matrícula(s) exibida(s) na tela. Use a busca para filtrar instantaneamente. Nada foi salvo no banco.`);if(!result.nextPage)break;page=result.nextPage}}catch(e){setError(e instanceof Error?`${e.message} ${totalLoaded?`${totalLoaded} matrícula(s) ficaram somente na tela.`:""}`:"Não foi possível concluir a consulta.")}finally{setBusy("")}}
  async function saveSyncYears(){const years=selectedSyncYears.slice().sort((a,b)=>a-b);await act("save-years",()=>run("save_years",{syncYears:years}))}
  async function syncSelectedYears(){const years=selectedSyncYears.length?selectedSyncYears:[selectedYear||config?.ano_letivo_ativo].filter(Boolean) as number[];setBusy("sync-years");setError("");setStudents([]);setSelectedMatriculaId(null);let totalLoaded=0;try{for(const year of years){let page=1;setMessage(`Atualizando espelho SWeduc do ano ${year}…`);while(page<=1000){const result=await run("sync",{page,academicYear:year});const loaded=result.students||[];totalLoaded+=loaded.length;if(year===selectedYear)setStudents(current=>[...current,...loaded]);setMessage(result.nextPage?`Ano ${year}: página ${page} de ${result.lastPage||"…"} · ${totalLoaded} matrícula(s) atualizada(s).`:`Ano ${year} concluído. Total atualizado até agora: ${totalLoaded} matrícula(s).`);if(!result.nextPage)break;page=result.nextPage}}setMessage(`Espelho SWeduc atualizado para ${years.join(", ")}. Foram consultadas ${totalLoaded} matrícula(s).`) }catch(e){setError(e instanceof Error?e.message:"Não foi possível sincronizar os anos selecionados.")}finally{setBusy("")}}
  function toggleSyncYear(year:number){setSelectedSyncYears(current=>current.includes(year)?current.filter(item=>item!==year):[...current,year].sort((a,b)=>a-b))}
  async function importSelectedStudent(){if(!selectedStudent)return;setBusy("import");setError("");setMessage("");try{const result=await run("import",{matriculaId:selectedStudent.matricula_id,responsibleIndex:selectedResponsibleIndex,student:selectedStudent});setMessage(result.message||"Aluno carregado para emissão.");if(result.student?.id){sessionStorage.setItem("jpi-assistant-student-focus",String(result.student.id));onNavigate?.("Assistente de emissão")}}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar este aluno para a nota.")}finally{setBusy("")}}
  async function revealSecrets(){if(!isMaster||!accessToken)return;setSecretsBusy(true);setSecretsError("");setCopied("");try{const response=await authenticatedFetch("/api/integrations/sweduc/master-secrets",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({confirm:true}),cache:"no-store"});const data=await response.json().catch(()=>({})) as {secrets?:{grantType:SweducGrant;clientId:string;clientSecret:string;username:string;password:string};error?:string};if(response.status===401)window.dispatchEvent(new Event("jpi-session-invalid"));if(!response.ok||!data.secrets)throw new Error(data.error||"Não foi possível revelar as credenciais protegidas.");setMasterSecrets(data.secrets);setSecretsVisible(true)}catch(e){setSecretsError(e instanceof Error?e.message:"Não foi possível revelar as credenciais protegidas.")}finally{setSecretsBusy(false)}}
  function hideSecrets(){setSecretsVisible(false);setMasterSecrets(null);setCopied("");setSecretsError("")}
  function closeApiInfo(){setApiInfoOpen(false);hideSecrets()}
  async function copySecret(field:"clientId"|"clientSecret"|"username"|"password"){const value=masterSecrets?.[field];if(!value)return;try{await navigator.clipboard.writeText(value);setCopied(field);window.setTimeout(()=>setCopied(current=>current===field?"":current),1800)}catch{setSecretsError("Não foi possível copiar. Verifique a permissão da área de transferência do navegador.")}}
  async function copyBackendSecretName(){try{await navigator.clipboard.writeText("JPI_BACKEND_SECRET");setCopied("backendSecretName");window.setTimeout(()=>setCopied(current=>current==="backendSecretName"?"":current),1800)}catch{setSecretsError("Não foi possível copiar. Verifique a permissão da área de transferência do navegador.")}}
  const tone=config?.ultimo_status==="conectado"?"connected":config?.ultimo_status==="erro"?"disconnected":"pending";const label=config?.ultimo_status==="conectado"?"Conectado":config?.ultimo_status==="erro"?"Erro":config?.credencial_configurada?"Pendente":"Não configurado";
  const currentYear=new Date().getFullYear();const syncYearOptions=useMemo(()=>{const base=academicYears.map(year=>year.year).filter(year=>year>=currentYear-1);const selected=selectedSyncYears.filter(year=>year>=currentYear-1);return Array.from(new Set([...base,...selected,currentYear-1,currentYear,currentYear+1])).filter(year=>year>=currentYear-1).sort((a,b)=>a-b)},[academicYears,currentYear,selectedSyncYears]);
  const visibleStudents=useMemo(()=>{const term=search.trim().toLocaleLowerCase("pt-BR");if(!term)return students;return students.filter(student=>[student.nome,student.numero_matricula,String(student.matricula_id),student.turma,student.serie,student.curso,student.responsaveis[0]?.nome].filter(Boolean).some(value=>String(value).toLocaleLowerCase("pt-BR").includes(term)))},[students,search]);
  const selectedStudent=useMemo(()=>students.find(student=>student.matricula_id===selectedMatriculaId)||null,[students,selectedMatriculaId]);
  const selectedResponsible=selectedStudent?.responsaveis[selectedResponsibleIndex]||selectedStudent?.responsaveis[0]||null;
  const contact=selectedResponsible?.telefones?.[0]?.numero||selectedResponsible?.emails?.[0]?.email||"Sem contato";
  return <div className="integration-detail-panel"><div className="integration-detail-heading"><span className="integration-icon blue"><BookOpenCheck/></span><div><h2>SWeduc</h2><p>Alunos, matrículas, responsáveis e dados financeiros.</p></div><span className={`integration-state-badge ${tone}`}><i/>{label}</span></div>
    {error&&<div className="error-box">{error}</div>}{message&&<div className="success-box">{message}</div>}
    <div className="notice compact"><ShieldCheck/><span>Esta integração é independente da Agenda Edu. HOST, CLIENT_ID, CLIENT_SECRET, usuário e senha ficam protegidos no cofre do servidor e nunca aparecem em logs ou no código.</span></div>
    {isMaster&&<button type="button" className="agenda-api-info-button sweduc-api-info-button" onClick={()=>setApiInfoOpen(true)}><KeyRound/><span><strong>Informações API e credenciais SWeduc</strong><small>Consultar endpoints, dados salvos e credenciais protegidas.</small></span><ArrowUpRight/></button>}
    <form className="communication-channel-card data-form" onSubmit={save}><div className="communication-channel-head"><span className="integration-icon blue"><KeyRound/></span><div><h3>Conexão segura</h3><small>OAuth 2 · API oficial de Alunos</small></div></div>
      <label>HOST<input type="url" value={host} onChange={e=>{setHost(e.target.value);setTemporaryTest(null)}} placeholder="https://sua-escola.escolarsw.com.br" required disabled={!canEdit}/></label>
      <label>CLIENT_ID<input type="password" value={clientId} onChange={e=>{setClientId(e.target.value);setTemporaryTest(null)}} placeholder={config?.credencial_configurada?"Protegido — deixe vazio para manter":"CLIENT_ID fornecido pela SWeduc"} autoComplete="new-password" disabled={!canEdit}/></label>
      <label>CLIENT_SECRET<input type="password" value={clientSecret} onChange={e=>{setClientSecret(e.target.value);setTemporaryTest(null)}} placeholder={config?.credencial_configurada?"Protegido — deixe vazio para manter":"CLIENT_SECRET fornecido pela SWeduc"} autoComplete="new-password" disabled={!canEdit}/></label>
      {canEdit&&<><label>USUÁRIO<input type="text" value={username} onChange={event=>{setUsername(event.target.value);setTemporaryTest(null)}} autoComplete="off" disabled={Boolean(busy)} placeholder={config?.usuario_configurado?"Protegido — deixe vazio para manter":"Usuário da SWeduc"}/></label><label>SENHA<input type="password" value={password} onChange={event=>{setPassword(event.target.value);setTemporaryTest(null)}} autoComplete="new-password" disabled={Boolean(busy)} placeholder={config?.usuario_configurado?"Protegida — deixe vazio para manter":"Senha da SWeduc"}/></label></>}
      {isMaster&&canEdit&&<div className="sweduc-temporary-test"><div className="sweduc-temporary-test-copy"><ShieldCheck/><span><strong>Teste antes de gravar</strong><small>Valida OAuth, listagem e detalhes do ano letivo ativo diretamente na SWeduc. Nenhuma credencial ou aluno será salvo.</small></span></div><div className="sweduc-temporary-test-controls"><small className="sweduc-grant-help">Ano letivo considerado: {config?.ano_letivo_ativo||"identificado pela SWeduc"}.</small><button type="button" className="secondary" disabled={Boolean(busy)||!host.trim()||!clientId.trim()||!clientSecret.trim()||!username.trim()||!password} onClick={()=>void testUnsavedCredentials()}>{busy==="temporary-test"?"Testando permissões…":"Testar sem salvar"}</button></div></div>}
      {temporaryTest&&<div className="sweduc-temporary-result" role="status"><Check/><div><strong>Teste temporário aprovado</strong><span>{temporaryTest.message}</span><small>Ano letivo: {temporaryTest.checks.activeAcademicYear} · Fluxo: {temporaryTest.checks.grantType==="password"?"usuário e senha":"client_credentials"} · OAuth: confirmado · Listagem: confirmada · Detalhes: {temporaryTest.checks.studentDetails==="confirmed"?"confirmados":"não verificados porque não havia matrícula disponível"}</small></div></div>}
      {canEdit&&<div className="form-actions"><button className="primary" disabled={Boolean(busy)}>{busy==="save"?"Salvando conexão…":"Salvar conexão SWeduc"}</button><button type="button" className="secondary" disabled={Boolean(busy)||!config?.credencial_configurada} onClick={()=>void act("test",()=>run("test"))}>{busy==="test"?"Testando…":"Testar conexão com API"}</button></div>}
      {(config?.testada_em||config?.sincronizada_em)&&<small className="last-test">{config.testada_em&&`Último teste: ${new Date(config.testada_em).toLocaleString("pt-BR")}`}{config.sincronizada_em&&` · Última sincronização: ${new Date(config.sincronizada_em).toLocaleString("pt-BR")}`}</small>}
    </form>
    {isMaster&&canEdit&&<div className="communication-channel-card sweduc-sync-years-card"><div className="communication-channel-head"><span className="integration-icon blue"><RefreshCw/></span><div><h3>Anos sincronizados no espelho</h3><small>Escolha somente os anos recentes que devem alimentar a busca rápida. Anos antigos não entram na atualização automática.</small></div></div><div className="sweduc-sync-years-list">{syncYearOptions.map(year=><label key={year} className={selectedSyncYears.includes(year)?"selected":""}><input type="checkbox" checked={selectedSyncYears.includes(year)} onChange={()=>toggleSyncYear(year)}/><span>{year}{year===config?.ano_letivo_ativo?" · ativo":year>currentYear?" · próximo":""}</span></label>)}</div><div className="form-actions"><button type="button" className="primary" disabled={Boolean(busy)||!selectedSyncYears.length} onClick={()=>void saveSyncYears()}>{busy==="save-years"?"Salvando anos…":"Salvar anos do espelho"}</button><button type="button" className="secondary" disabled={Boolean(busy)||!config?.credencial_configurada||!selectedSyncYears.length} onClick={()=>void syncSelectedYears()}><RefreshCw size={17}/>{busy==="sync-years"?"Sincronizando…":"Sincronizar anos escolhidos"}</button></div><small className="last-test">Sugestão para agora: manter {currentYear-1}, {currentYear} e os próximos anos quando aparecerem na SWeduc.</small></div>}
    <div className="communication-channel-card"><div className="communication-channel-head"><span className="integration-icon blue"><UsersRound/></span><div><h3>Alunos por ano letivo</h3><small>{students.length} matrícula(s) consultada(s) de {selectedYear||config?.ano_letivo_ativo||"ano selecionado"} · {search.trim()?`${visibleStudents.length} exibida(s) pela busca rápida`:"busca rápida na lista carregada"} · nada salvo até carregar para a nota</small></div></div><div className="toolbar sweduc-year-toolbar"><label>Ano letivo<select value={selectedYear||""} onChange={event=>{const year=Number(event.target.value);setSelectedYear(year);setSelectedMatriculaId(null);setStudents([]);setSearch("");void load("",year).catch(e=>setError(e.message))}}>{academicYears.map(year=><option key={year.year} value={year.year}>{year.year}{year.year===config?.ano_letivo_ativo?" · ativo":""}</option>)}</select></label><div className="search-input"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Buscar rápido nos alunos carregados de ${selectedYear||"ano"}`}/></div><button type="button" className="secondary" disabled={Boolean(busy)||!config?.credencial_configurada} onClick={()=>void syncAll()}><RefreshCw size={17}/>{busy==="sync"?"Consultando…":"Consultar SWeduc"}</button><button type="button" className="secondary" onClick={()=>void syncAll()}>Atualizar grade</button></div>
      {!students.length&&<div className="notice compact warning"><RefreshCw/><span>Consulte a SWeduc pelo ano letivo escolhido. Os alunos aparecem apenas nesta tela; o banco só será gravado quando você selecionar um aluno e clicar em Carregar para a nota.</span></div>}
      <div className="sweduc-selection-grid"><div className="table-card"><table><thead><tr><th>Ano letivo</th><th>Aluno</th><th>Matrícula</th><th>Turma / série</th><th>Responsável financeiro</th><th>Financeiro</th><th></th></tr></thead><tbody>{visibleStudents.map(student=><tr key={student.matricula_id} className={selectedMatriculaId===student.matricula_id?"selected-row":""} onClick={()=>{setSelectedMatriculaId(student.matricula_id);setSelectedResponsibleIndex(0)}}><td><strong>{student.ano_letivo||selectedYear||"—"}</strong><span className="subcell">{student.status||"Situação não informada"}</span></td><td><strong>{student.nome}</strong><span className="subcell">{student.unidade||"Unidade não informada"}</span></td><td>{student.numero_matricula||student.matricula_id}<span className="subcell">ID {student.matricula_id}</span></td><td>{[student.turma,student.serie].filter(Boolean).join(" · ")||"—"}<span className="subcell">{student.curso||""}</span></td><td>{student.responsaveis[0]?.nome||"Não informado"}<span className="subcell">{student.responsaveis[0]?.telefones?.[0]?.numero||student.responsaveis[0]?.emails?.[0]?.email||(student.detalhes_carregados?"Sem contato":"Detalhes não carregados")}</span></td><td>{student.financeiro.length?`${student.financeiro.length} título(s) disponível(is)`:"Sem dados"}</td><td><button type="button" className="secondary mini" onClick={event=>{event.stopPropagation();setSelectedMatriculaId(student.matricula_id);setSelectedResponsibleIndex(0)}}>{selectedMatriculaId===student.matricula_id?"Selecionado":"Selecionar"}</button></td></tr>)}{!visibleStudents.length&&<tr><td colSpan={7}>{students.length?"Nenhum aluno encontrado na busca rápida.":"Nenhum aluno sincronizado ou encontrado para este ano."}</td></tr>}</tbody></table></div>
      <aside className="sweduc-import-panel">{!selectedStudent?<div className="assistant-empty large"><UsersRound/><strong>Selecione um aluno</strong><span>Depois escolha o responsável que será usado como tomador da nota.</span></div>:<><div><small>MATRÍCULA SELECIONADA</small><h3>{selectedStudent.nome}</h3><p>{[selectedStudent.turma,selectedStudent.serie,selectedStudent.curso].filter(Boolean).join(" · ")||"Turma não informada"}</p></div><label>Responsável para a nota<select value={selectedResponsibleIndex} onChange={event=>setSelectedResponsibleIndex(Number(event.target.value))}>{(selectedStudent.responsaveis.length?selectedStudent.responsaveis:[{nome:"Responsável não informado"}]).map((responsible,index)=><option key={index} value={index}>{responsible.nome||`Responsável ${index+1}`}</option>)}</select></label><div className="sweduc-import-summary"><span><small>Contato</small><strong>{contact}</strong></span><span><small>Financeiro</small><strong>{selectedStudent.financeiro.length?`${selectedStudent.financeiro.length} título(s)`:"Sem dados"}</strong></span><span><small>Situação</small><strong>{selectedStudent.status||"Não informado"}</strong></span></div><button type="button" className="primary" disabled={Boolean(busy)||!canEdit} onClick={()=>void importSelectedStudent()}>{busy==="import"?"Carregando…":"Carregar para a nota"}<ChevronRight size={17}/></button><small>O cadastro fiscal será criado ou atualizado pela matrícula SWeduc e aberto no Assistente de Emissão.</small></>}</aside></div>
    </div>
    {isMaster&&apiInfoOpen&&<div className="agenda-api-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target)closeApiInfo()}}>
      <section className="agenda-api-modal sweduc-api-modal" role="dialog" aria-modal="true" aria-labelledby="sweduc-api-modal-title">
        <header className="agenda-api-modal-head">
          <div className="agenda-api-modal-title"><span><KeyRound/></span><div><small>ACESSO EXCLUSIVO DO MASTER</small><h2 id="sweduc-api-modal-title">Informações API e credenciais SWeduc</h2><p>Dados de conexão guardados para consulta e manutenção futura da integração.</p></div></div>
          <button type="button" className="agenda-api-modal-close" onClick={closeApiInfo} aria-label="Fechar"><X/></button>
        </header>
        <div className="agenda-api-modal-body">
          <section className="agenda-api-status-card">
            <div className="agenda-api-status-copy"><span className={config?.ultimo_status==="conectado"?"connected":config?.ultimo_status==="erro"?"error":"pending"}></span><div><small>STATUS DA INTEGRAÇÃO</small><strong>{config?.ultimo_status==="conectado"?"SWeduc conectada":config?.ultimo_status==="erro"?"SWeduc com erro":"SWeduc pendente"}</strong><p>{config?.credencial_configurada?"Credenciais guardadas no cofre seguro do servidor.":"Credenciais ainda não cadastradas."}</p></div></div>
            <span className="master-only-badge">MASTER</span>
          </section>
          <div className="agenda-api-modal-grid">
            <section className="agenda-api-info-section">
              <div className="agenda-api-section-title"><Link2/><div><strong>Conexão e endpoints</strong><small>Referência rápida para manutenção futura.</small></div></div>
              <dl className="agenda-api-data-list">
                <div><dt>HOST</dt><dd className="mono">{config?.host||"Não informado"}</dd></div>
                <div><dt>Autenticação salva</dt><dd>{config?.auth_method==="password"?"OAuth 2 · usuário e senha (password)":"OAuth 2 · client_credentials"}</dd></div>
                <div><dt>Credenciais do cliente</dt><dd>HTTP Basic Authentication</dd></div>
                <div><dt>Ano letivo ativo</dt><dd>{config?.ano_letivo_ativo||"Não identificado"}</dd></div>
                <div><dt>Obter token</dt><dd className="mono">POST /oauth/v2/token</dd></div>
                <div><dt>Consultar anos</dt><dd className="mono">GET /api/public/v1/academico/anos-letivos</dd></div>
                <div><dt>Listar alunos</dt><dd className="mono">GET /api/v2/alunos/listar</dd></div>
                <div><dt>Detalhar matrícula</dt><dd className="mono">GET /api/v2/alunos/detalhes?matricula_id=...</dd></div>
                <div><dt>Documentação</dt><dd><a className="sweduc-api-doc-link" href="https://assets.sweduc.com.br/assets-website/docs_api_alunos.html" target="_blank" rel="noreferrer">Abrir documentação oficial <ArrowUpRight/></a></dd></div>
              </dl>
            </section>
            <section className="agenda-api-info-section credentials">
              <div className="agenda-api-section-title"><ShieldCheck/><div><strong>Credenciais protegidas</strong><small>Carregadas do cofre somente quando o Master solicitar.</small></div></div>
              <div className="agenda-api-credential-list">
                <div><label>CLIENT_ID</label><div><span className={secretsVisible?"revealed":"masked"}>{secretsVisible&&masterSecrets?.clientId?masterSecrets.clientId:"••••••••••••••••••••"}</span><button type="button" disabled={!secretsVisible||!masterSecrets?.clientId} onClick={()=>void copySecret("clientId")} title="Copiar CLIENT_ID">{copied==="clientId"?<Check/>:<Copy/>}</button></div></div>
                <div><label>CLIENT_SECRET</label><div><span className={secretsVisible?"revealed":"masked"}>{secretsVisible&&masterSecrets?.clientSecret?masterSecrets.clientSecret:"••••••••••••••••••••"}</span><button type="button" disabled={!secretsVisible||!masterSecrets?.clientSecret} onClick={()=>void copySecret("clientSecret")} title="Copiar CLIENT_SECRET">{copied==="clientSecret"?<Check/>:<Copy/>}</button></div></div>
                {config?.auth_method==="password"&&<div><label>USUÁRIO</label><div><span className={secretsVisible?"revealed":"masked"}>{secretsVisible&&masterSecrets?.username?masterSecrets.username:"••••••••••••••••••••"}</span><button type="button" disabled={!secretsVisible||!masterSecrets?.username} onClick={()=>void copySecret("username")} title="Copiar USUÁRIO">{copied==="username"?<Check/>:<Copy/>}</button></div></div>}
                {config?.auth_method==="password"&&<div><label>SENHA</label><div><span className={secretsVisible?"revealed":"masked"}>{secretsVisible&&masterSecrets?.password?masterSecrets.password:"••••••••••••••••••••"}</span><button type="button" disabled={!secretsVisible||!masterSecrets?.password} onClick={()=>void copySecret("password")} title="Copiar SENHA">{copied==="password"?<Check/>:<Copy/>}</button></div></div>}
              </div>
              <div className="agenda-api-secret-actions">
                {!secretsVisible?<button type="button" className="primary" onClick={()=>void revealSecrets()} disabled={secretsBusy||!config?.credencial_configurada}><Eye/>{secretsBusy?"Carregando…":"Revelar credenciais"}</button>:<button type="button" className="secondary" onClick={hideSecrets}><EyeOff/>Ocultar credenciais</button>}
                <small>Os valores revelados ficam disponíveis por no máximo 60 segundos e não são salvos no navegador.</small>
                {secretsError&&<span className="agenda-secret-error">{secretsError}</span>}
              </div>
            </section>
            <section className="agenda-api-info-section credentials">
              <div className="agenda-api-section-title"><ShieldCheck/><div><strong>Cofre seguro do servidor</strong><small>Chave técnica usada pelo servidor para abrir o cofre interno do JPI Fiscal.</small></div></div>
              <div className="agenda-api-credential-list">
                <div><label>STATUS DO COFRE</label><div><span className={config?.cofre_configurado?"revealed":"masked"}>{config?.cofre_configurado?"Configurado na Vercel":"Não configurado na Vercel"}</span></div></div>
                <div><label>NOME DA VARIÁVEL</label><div><span className="revealed mono">JPI_BACKEND_SECRET</span><button type="button" onClick={()=>void copyBackendSecretName()} title="Copiar nome da variável">{copied==="backendSecretName"?<Check/>:<Copy/>}</button></div></div>
                <div><label>ONDE FICA</label><div><span className="revealed">Vercel › jpi-fiscal › Settings › Environment Variables</span></div></div>
              </div>
              <div className="agenda-api-secret-actions">
                <small>Por segurança, o valor dessa chave mestra não é exibido nem armazenado nesta tela. Ela precisa ficar somente no ambiente do servidor.</small>
              </div>
            </section>
          </div>
          <div className="agenda-api-security-note"><ShieldCheck/><div><strong>Proteção mantida</strong><span>Somente o perfil Master consegue abrir esta janela e solicitar os valores reais ao servidor.</span></div></div>
        </div>
      </section>
    </div>}
  </div>;
}
