create table if not exists public.nfse_entregas (
  id bigint generated by default as identity primary key,
  mensalidade_id bigint not null references public.mensalidades(id) on delete restrict,
  documento_homologacao_id bigint not null references public.nfse_documentos_homologacao(id) on delete restrict,
  request_id uuid not null unique,
  canal text not null default 'email' check (canal in ('email')),
  ambiente text not null default 'homologacao' check (ambiente in ('homologacao','producao')),
  destinatario_pretendido text not null,
  destinatario_utilizado text not null,
  assunto text not null,
  status text not null default 'enviando' check (status in ('enviando','enviado','erro')),
  provider_message_id text,
  erro_mensagem text,
  enviado_em timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid not null,
  updated_at timestamptz not null default now()
);

create index if not exists nfse_entregas_mensalidade_idx
  on public.nfse_entregas (mensalidade_id, created_at desc);

create index if not exists nfse_entregas_documento_idx
  on public.nfse_entregas (documento_homologacao_id, created_at desc);

create unique index if not exists nfse_entregas_envio_em_andamento_idx
  on public.nfse_entregas (documento_homologacao_id, canal, ambiente)
  where status = 'enviando';

alter table public.nfse_entregas enable row level security;
revoke all on table public.nfse_entregas from anon;
grant select, insert, update on table public.nfse_entregas to authenticated;
grant usage, select on sequence public.nfse_entregas_id_seq to authenticated;

drop policy if exists "Perfis fiscais visualizam entregas" on public.nfse_entregas;
create policy "Perfis fiscais visualizam entregas"
on public.nfse_entregas for select
to authenticated
using ((select private.current_jpi_role()) = any (array['admin'::text,'financeiro'::text,'consulta'::text]));

drop policy if exists "Perfis fiscais registram entregas" on public.nfse_entregas;
create policy "Perfis fiscais registram entregas"
on public.nfse_entregas for insert
to authenticated
with check (
  (select private.current_jpi_role()) = any (array['admin'::text,'financeiro'::text])
  and created_by = (select auth.uid())
  and ambiente = 'homologacao'
  and destinatario_utilizado = 'nfse@jejoaopaulo.com.br'
);

drop policy if exists "Perfis fiscais atualizam entregas" on public.nfse_entregas;
create policy "Perfis fiscais atualizam entregas"
on public.nfse_entregas for update
to authenticated
using (
  (select private.current_jpi_role()) = any (array['admin'::text,'financeiro'::text])
  and created_by = (select auth.uid())
)
with check (
  (select private.current_jpi_role()) = any (array['admin'::text,'financeiro'::text])
  and created_by = (select auth.uid())
  and ambiente = 'homologacao'
  and destinatario_utilizado = 'nfse@jejoaopaulo.com.br'
);

create or replace function private.get_email_delivery_config_internal(p_backend_secret text)
returns table (
  email_provider text,
  email_from_name text,
  email_from_address text,
  email_reply_to text,
  email_smtp_host text,
  email_smtp_port integer,
  email_smtp_username text,
  email_credencial_configurada boolean,
  email_ultimo_status text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or private.current_jpi_role() not in ('admin','financeiro') then
    raise exception 'Usuário sem permissão para enviar documentos.' using errcode = '42501';
  end if;
  if not private.valid_jpi_backend_secret(p_backend_secret) then
    raise exception 'Credencial interna do servidor inválida.' using errcode = '42501';
  end if;
  return query
  select
    config.email_provider,
    config.email_from_name,
    config.email_from_address,
    config.email_reply_to,
    config.email_smtp_host,
    config.email_smtp_port,
    config.email_smtp_username,
    config.email_credencial_configurada,
    config.email_ultimo_status
  from public.integracoes_comunicacao as config
  where config.id = true;
end;
$$;

revoke all on function private.get_email_delivery_config_internal(text) from public, anon;
grant execute on function private.get_email_delivery_config_internal(text) to authenticated;

create or replace function public.get_email_delivery_config(p_backend_secret text)
returns table (
  email_provider text,
  email_from_name text,
  email_from_address text,
  email_reply_to text,
  email_smtp_host text,
  email_smtp_port integer,
  email_smtp_username text,
  email_credencial_configurada boolean,
  email_ultimo_status text
)
language sql
security invoker
set search_path = ''
as $$
  select * from private.get_email_delivery_config_internal(p_backend_secret);
$$;

revoke all on function public.get_email_delivery_config(text) from public, anon;
grant execute on function public.get_email_delivery_config(text) to authenticated;
