create table if not exists public.whatsapp_manual_senders (
  id bigint generated by default as identity primary key,
  nome text not null,
  numero text not null unique,
  ativo boolean not null default true,
  ordem smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid,
  constraint whatsapp_manual_senders_nome_check check (length(trim(nome)) between 1 and 60),
  constraint whatsapp_manual_senders_numero_check check (numero ~ '^55[1-9][0-9]{9,10}$'),
  constraint whatsapp_manual_senders_ordem_check check (ordem between 1 and 4)
);

alter table public.whatsapp_manual_senders enable row level security;
revoke all on table public.whatsapp_manual_senders from anon;
grant select, insert, update, delete on table public.whatsapp_manual_senders to authenticated;
grant usage, select on sequence public.whatsapp_manual_senders_id_seq to authenticated;

drop policy if exists "Perfis fiscais visualizam remetentes WhatsApp" on public.whatsapp_manual_senders;
create policy "Perfis fiscais visualizam remetentes WhatsApp"
on public.whatsapp_manual_senders for select
to authenticated
using ((select private.current_jpi_role()) = any (array['admin'::text,'financeiro'::text]));

drop policy if exists "Administrador cadastra remetentes WhatsApp" on public.whatsapp_manual_senders;
create policy "Administrador cadastra remetentes WhatsApp"
on public.whatsapp_manual_senders for insert
to authenticated
with check ((select private.current_jpi_role()) = 'admin');

drop policy if exists "Administrador atualiza remetentes WhatsApp" on public.whatsapp_manual_senders;
create policy "Administrador atualiza remetentes WhatsApp"
on public.whatsapp_manual_senders for update
to authenticated
using ((select private.current_jpi_role()) = 'admin')
with check ((select private.current_jpi_role()) = 'admin');

drop policy if exists "Administrador remove remetentes WhatsApp" on public.whatsapp_manual_senders;
create policy "Administrador remove remetentes WhatsApp"
on public.whatsapp_manual_senders for delete
to authenticated
using ((select private.current_jpi_role()) = 'admin');

create or replace function public.replace_whatsapp_manual_senders(p_senders jsonb)
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  item jsonb;
  normalized text;
  sender_name text;
  sender_active boolean;
  sender_order integer;
  inserted_count integer := 0;
begin
  if auth.uid() is null or private.current_jpi_role() <> 'admin' then
    raise exception 'Apenas o Administrador pode configurar os números do WhatsApp.' using errcode = '42501';
  end if;

  if p_senders is null or jsonb_typeof(p_senders) <> 'array' or jsonb_array_length(p_senders) > 4 then
    raise exception 'Cadastre no máximo 4 números de WhatsApp.' using errcode = '22023';
  end if;

  delete from public.whatsapp_manual_senders;

  for item in select value from jsonb_array_elements(p_senders)
  loop
    sender_name := trim(coalesce(item->>'nome',''));
    normalized := regexp_replace(coalesce(item->>'numero',''), '[^0-9]', '', 'g');
    if length(normalized) in (10,11) then normalized := '55' || normalized; end if;
    sender_active := coalesce((item->>'ativo')::boolean, true);
    sender_order := coalesce((item->>'ordem')::integer, inserted_count + 1);

    if length(sender_name) < 1 or length(sender_name) > 60 then
      raise exception 'Informe um nome válido para cada WhatsApp.' using errcode = '22023';
    end if;
    if normalized !~ '^55[1-9][0-9]{9,10}$' then
      raise exception 'Informe números brasileiros válidos com DDD.' using errcode = '22023';
    end if;
    if sender_order < 1 or sender_order > 4 then
      raise exception 'A ordem dos números do WhatsApp é inválida.' using errcode = '22023';
    end if;

    insert into public.whatsapp_manual_senders (nome, numero, ativo, ordem, updated_by)
    values (sender_name, normalized, sender_active, sender_order, auth.uid());
    inserted_count := inserted_count + 1;
  end loop;

  return inserted_count;
end;
$$;

revoke all on function public.replace_whatsapp_manual_senders(jsonb) from public, anon;
grant execute on function public.replace_whatsapp_manual_senders(jsonb) to authenticated;

alter table public.nfse_entregas
  add column if not exists whatsapp_sender_id bigint references public.whatsapp_manual_senders(id) on delete set null,
  add column if not exists whatsapp_sender_nome text,
  add column if not exists whatsapp_sender_numero text;

alter table public.nfse_entregas
  drop constraint if exists nfse_entregas_whatsapp_sender_numero_check;
alter table public.nfse_entregas
  add constraint nfse_entregas_whatsapp_sender_numero_check
  check (whatsapp_sender_numero is null or whatsapp_sender_numero ~ '^55[1-9][0-9]{9,10}$');

create index if not exists nfse_entregas_whatsapp_sender_idx
  on public.nfse_entregas (whatsapp_sender_id, created_at desc);

create or replace function private.get_delivery_dashboard_internal(
  p_start timestamptz default null,
  p_end timestamptz default null
)
returns table (
  canal text,
  enviados bigint,
  erros bigint,
  aguardando bigint,
  ultima_atividade timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null
     or private.current_jpi_role() not in ('admin','financeiro','secretaria','consulta') then
    raise exception 'Usuário sem permissão para visualizar o painel.' using errcode = '42501';
  end if;

  return query
  select
    case
      when e.canal in ('whatsapp','whatsapp_manual') then 'whatsapp'
      when e.canal = 'agenda_edu' then 'agenda_edu'
      else 'email'
    end as canal,
    count(*) filter (where e.status = 'enviado') as enviados,
    count(*) filter (where e.status = 'erro') as erros,
    count(*) filter (where e.status in ('enviando','aguardando_confirmacao')) as aguardando,
    max(coalesce(e.enviado_em,e.updated_at,e.created_at)) as ultima_atividade
  from public.nfse_entregas e
  where (p_start is null or e.created_at >= p_start)
    and (p_end is null or e.created_at < p_end)
  group by 1
  order by 1;
end;
$$;

revoke all on function private.get_delivery_dashboard_internal(timestamptz,timestamptz) from public, anon;
grant execute on function private.get_delivery_dashboard_internal(timestamptz,timestamptz) to authenticated;

create or replace function public.get_delivery_dashboard(
  p_start timestamptz default null,
  p_end timestamptz default null
)
returns table (
  canal text,
  enviados bigint,
  erros bigint,
  aguardando bigint,
  ultima_atividade timestamptz
)
language sql
security invoker
set search_path = ''
as $$
  select * from private.get_delivery_dashboard_internal(p_start,p_end);
$$;

revoke all on function public.get_delivery_dashboard(timestamptz,timestamptz) from public, anon;
grant execute on function public.get_delivery_dashboard(timestamptz,timestamptz) to authenticated;

comment on table public.whatsapp_manual_senders is
  'Até quatro contas de WhatsApp da escola disponíveis para escolha no envio manual. O sistema registra a conta escolhida, mas o WhatsApp Web/app controla a conta efetivamente conectada.';
comment on column public.nfse_entregas.whatsapp_sender_nome is
  'Nome da conta de WhatsApp escolhida no momento do envio manual, preservado para auditoria.';
comment on column public.nfse_entregas.whatsapp_sender_numero is
  'Número da conta de WhatsApp escolhida no momento do envio manual, preservado para auditoria.';
