create table if not exists public.nfse_documentos_homologacao (
  id bigint generated by default as identity primary key,
  mensalidade_id bigint not null references public.mensalidades(id) on delete cascade,
  versao integer not null check (versao > 0),
  chave_acesso text not null unique check (chave_acesso ~ '^[0-9]{50}$'),
  dps_xml_id text,
  dps_xml_path text,
  dps_assinada_xml_path text,
  nfse_xml_path text not null,
  estado text not null default 'ativa' check (estado in ('ativa', 'cancelando', 'cancelada', 'substituindo', 'substituida')),
  substitui_documento_id bigint references public.nfse_documentos_homologacao(id),
  emitida_em timestamptz not null,
  evento_xml_path text,
  evento_motivo_codigo text,
  evento_motivo_descricao text,
  evento_processado_em timestamptz,
  created_at timestamptz not null default now(),
  unique (mensalidade_id, versao)
);

comment on table public.nfse_documentos_homologacao is
  'Versões imutáveis das NFS-e geradas na produção restrita, incluindo cancelamentos e substituições.';
comment on column public.nfse_documentos_homologacao.estado is
  'Situação da versão no ambiente de homologação; somente uma versão corrente pode existir por mensalidade.';

create unique index if not exists nfse_documentos_hml_uma_corrente_por_mensalidade
  on public.nfse_documentos_homologacao (mensalidade_id)
  where estado in ('ativa', 'cancelando', 'substituindo');

create index if not exists nfse_documentos_hml_mensalidade_versao_idx
  on public.nfse_documentos_homologacao (mensalidade_id, versao desc);

create index if not exists nfse_documentos_hml_substitui_documento_idx
  on public.nfse_documentos_homologacao (substitui_documento_id)
  where substitui_documento_id is not null;

alter table public.nfse_documentos_homologacao enable row level security;

revoke all on table public.nfse_documentos_homologacao from anon;
grant select, insert, update on table public.nfse_documentos_homologacao to authenticated;
grant usage, select on sequence public.nfse_documentos_homologacao_id_seq to authenticated;

drop policy if exists nfse_documentos_hml_select on public.nfse_documentos_homologacao;
create policy nfse_documentos_hml_select
  on public.nfse_documentos_homologacao
  for select
  to authenticated
  using (private.current_jpi_role() = any (array['admin'::text, 'financeiro'::text, 'secretaria'::text, 'consulta'::text]));

drop policy if exists nfse_documentos_hml_insert on public.nfse_documentos_homologacao;
create policy nfse_documentos_hml_insert
  on public.nfse_documentos_homologacao
  for insert
  to authenticated
  with check (private.current_jpi_role() = any (array['admin'::text, 'financeiro'::text]));

drop policy if exists nfse_documentos_hml_update on public.nfse_documentos_homologacao;
create policy nfse_documentos_hml_update
  on public.nfse_documentos_homologacao
  for update
  to authenticated
  using (private.current_jpi_role() = any (array['admin'::text, 'financeiro'::text]))
  with check (private.current_jpi_role() = any (array['admin'::text, 'financeiro'::text]));

drop policy if exists nfse_documentos_hml_delete on public.nfse_documentos_homologacao;
create policy nfse_documentos_hml_delete
  on public.nfse_documentos_homologacao
  for delete
  to authenticated
  using (private.current_jpi_role() = any (array['admin'::text, 'financeiro'::text]));

insert into public.nfse_documentos_homologacao (
  mensalidade_id,
  versao,
  chave_acesso,
  dps_xml_id,
  dps_xml_path,
  dps_assinada_xml_path,
  nfse_xml_path,
  estado,
  emitida_em
)
select
  m.id,
  1,
  m.chave_nfse_homologacao,
  m.dps_xml_id,
  m.dps_xml_path,
  m.dps_assinada_xml_path,
  m.nfse_homologacao_xml_path,
  'ativa',
  coalesce(m.homologacao_emitida_em, now())
from public.mensalidades m
where m.chave_nfse_homologacao is not null
  and m.nfse_homologacao_xml_path is not null
on conflict (chave_acesso) do nothing;
