create table if not exists public.lgpd_user_acceptances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_email text,
  user_role text,
  term_version text not null,
  term_title text not null,
  acceptance_text text not null,
  acceptance_hash text not null,
  ip_address inet,
  user_agent text,
  accepted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(user_id,term_version)
);

alter table public.lgpd_user_acceptances enable row level security;
revoke all on public.lgpd_user_acceptances from anon;
grant select,insert,update on public.lgpd_user_acceptances to authenticated;
grant usage,select on sequence public.lgpd_user_acceptances_id_seq to authenticated;

drop policy if exists lgpd_acceptances_own_select on public.lgpd_user_acceptances;
create policy lgpd_acceptances_own_select on public.lgpd_user_acceptances
  for select
  to authenticated
  using ((select auth.uid())=user_id or private.current_jpi_raw_role()='master');

drop policy if exists lgpd_acceptances_own_insert on public.lgpd_user_acceptances;
create policy lgpd_acceptances_own_insert on public.lgpd_user_acceptances
  for insert
  to authenticated
  with check ((select auth.uid())=user_id);

drop policy if exists lgpd_acceptances_own_update on public.lgpd_user_acceptances;
create policy lgpd_acceptances_own_update on public.lgpd_user_acceptances
  for update
  to authenticated
  using ((select auth.uid())=user_id)
  with check ((select auth.uid())=user_id);

create index if not exists lgpd_user_acceptances_user_idx on public.lgpd_user_acceptances(user_id);
create index if not exists lgpd_user_acceptances_version_idx on public.lgpd_user_acceptances(term_version,accepted_at desc);
