create table if not exists public.monthly_closings (
  id bigint generated by default as identity primary key,
  competence text not null check (competence ~ '^20[0-9]{2}-(0[1-9]|1[0-2])$'),
  status text not null default 'closed' check (status in ('closed','reopened')),
  snapshot jsonb not null,
  closed_by bigint references public.app_users(id) on delete set null,
  closed_by_name text not null,
  closed_at timestamptz not null default now(),
  reopened_by bigint references public.app_users(id) on delete set null,
  reopened_by_name text,
  reopened_at timestamptz,
  reopen_reason text,
  created_at timestamptz not null default now()
);

create unique index if not exists monthly_closings_one_active_idx
  on public.monthly_closings(competence) where status='closed';
create index if not exists monthly_closings_competence_history_idx
  on public.monthly_closings(competence,closed_at desc);

alter table public.monthly_closings enable row level security;
revoke all on table public.monthly_closings from anon,authenticated;
grant select on table public.monthly_closings to authenticated;

drop policy if exists monthly_closings_select on public.monthly_closings;
create policy monthly_closings_select on public.monthly_closings
for select to authenticated
using (private.has_jpi_permission('dashboard.view'));

insert into public.jpi_permissions(permission_key,module_key,module_label,action_key,action_label,description,sort_order)
values ('dashboard.close','dashboard','Painel','close','Fechar competência','Fechar a competência mensal após eliminar todas as pendências.',11)
on conflict(permission_key) do update set
 module_key=excluded.module_key,module_label=excluded.module_label,action_key=excluded.action_key,
 action_label=excluded.action_label,description=excluded.description,sort_order=excluded.sort_order;

insert into public.jpi_role_permissions(role,permission_key,allowed)
values ('admin','dashboard.close',true),('financeiro','dashboard.close',true),('secretaria','dashboard.close',false),('consulta','dashboard.close',false)
on conflict(role,permission_key) do nothing;

create or replace function public.close_monthly_competence(p_competence text,p_snapshot jsonb)
returns bigint
language plpgsql
security definer
set search_path=''
as $$
declare
  v_user public.app_users%rowtype;
  v_id bigint;
begin
  if auth.uid() is null or not private.has_jpi_permission('dashboard.close') then
    raise exception 'Usuário sem permissão para fechar competências.' using errcode='42501';
  end if;
  if p_competence !~ '^20[0-9]{2}-(0[1-9]|1[0-2])$' then
    raise exception 'Competência inválida.' using errcode='22023';
  end if;
  if coalesce((p_snapshot->>'pendencies')::integer,0)>0 then
    raise exception 'Resolva as pendências antes de fechar a competência.' using errcode='22023';
  end if;
  if coalesce((p_snapshot->>'payments')::integer,0)=0 then
    raise exception 'Não há movimentação para fechar nesta competência.' using errcode='22023';
  end if;
  select * into v_user from public.app_users
  where lower(email)=lower(auth.jwt()->>'email') and active=true limit 1;
  if v_user.id is null then raise exception 'Usuário não encontrado.' using errcode='42501'; end if;
  insert into public.monthly_closings(competence,snapshot,closed_by,closed_by_name)
  values(p_competence,p_snapshot,v_user.id,v_user.nome) returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.reopen_monthly_competence(p_closing_id bigint,p_reason text)
returns boolean
language plpgsql
security definer
set search_path=''
as $$
declare v_user public.app_users%rowtype;
begin
  if auth.uid() is null or private.current_jpi_raw_role()<>'master' then
    raise exception 'Somente o Master pode reabrir uma competência.' using errcode='42501';
  end if;
  if length(trim(coalesce(p_reason,'')))<10 then
    raise exception 'Informe um motivo com pelo menos 10 caracteres.' using errcode='22023';
  end if;
  select * into v_user from public.app_users
  where lower(email)=lower(auth.jwt()->>'email') and active=true limit 1;
  update public.monthly_closings set status='reopened',reopened_by=v_user.id,
    reopened_by_name=v_user.nome,reopened_at=now(),reopen_reason=trim(p_reason)
  where id=p_closing_id and status='closed';
  if not found then raise exception 'Fechamento ativo não encontrado.' using errcode='P0002'; end if;
  return true;
end;
$$;

revoke all on function public.close_monthly_competence(text,jsonb) from public,anon;
revoke all on function public.reopen_monthly_competence(bigint,text) from public,anon;
grant execute on function public.close_monthly_competence(text,jsonb) to authenticated;
grant execute on function public.reopen_monthly_competence(bigint,text) to authenticated;


