alter table public.nfse_entregas
  add column if not exists provider_aceito_em timestamptz,
  add column if not exists visualizado_em timestamptz,
  add column if not exists visualizacoes integer not null default 0 check (visualizacoes >= 0);

create table if not exists private.nfse_entrega_links (
  id bigint generated by default as identity primary key,
  entrega_id bigint not null unique references public.nfse_entregas(id) on delete cascade,
  token_hash text not null unique check (token_hash ~ '^[a-f0-9]{64}$'),
  chave_acesso text not null,
  xml_content bytea not null check (octet_length(xml_content) between 1 and 10485760),
  expires_at timestamptz not null,
  visualizado_em timestamptz,
  ultimo_acesso_em timestamptz,
  visualizacoes integer not null default 0 check (visualizacoes >= 0),
  created_at timestamptz not null default now()
);

revoke all on table private.nfse_entrega_links from public, anon, authenticated;

create index if not exists nfse_entrega_links_expiracao_idx
  on private.nfse_entrega_links (expires_at);

create or replace function private.create_nfse_delivery_access_internal(
  p_delivery_id bigint,
  p_token_hash text,
  p_xml_base64 text,
  p_chave_acesso text,
  p_backend_secret text
)
returns timestamptz
language plpgsql
security definer
set search_path = ''
as $$
declare
  expiry timestamptz := now() + interval '365 days';
  decoded_xml bytea;
begin
  if auth.uid() is null or private.current_jpi_role() not in ('admin','financeiro') then
    raise exception 'Usuário sem permissão para criar acesso à nota.' using errcode = '42501';
  end if;
  if not private.valid_jpi_backend_secret(p_backend_secret) then
    raise exception 'Credencial interna do servidor inválida.' using errcode = '42501';
  end if;
  if p_token_hash is null or p_token_hash !~ '^[a-f0-9]{64}$'
     or p_xml_base64 is null or length(p_xml_base64) > 14000000
     or p_chave_acesso is null or length(p_chave_acesso) > 80 then
    raise exception 'Dados do acesso protegido inválidos.' using errcode = '22023';
  end if;
  select decode(p_xml_base64, 'base64') into decoded_xml;
  if octet_length(decoded_xml) not between 1 and 10485760 then
    raise exception 'Documento fora do limite permitido.' using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.nfse_entregas e
    where e.id = p_delivery_id and e.created_by = auth.uid()
      and e.canal = 'agenda_edu' and e.ambiente = 'homologacao'
  ) then
    raise exception 'Entrega protegida não encontrada.' using errcode = '42501';
  end if;
  insert into private.nfse_entrega_links(entrega_id,token_hash,chave_acesso,xml_content,expires_at)
  values(p_delivery_id,p_token_hash,p_chave_acesso,decoded_xml,expiry)
  on conflict (entrega_id) do update set
    token_hash=excluded.token_hash,
    chave_acesso=excluded.chave_acesso,
    xml_content=excluded.xml_content,
    expires_at=excluded.expires_at;
  return expiry;
end;
$$;

create or replace function public.create_nfse_delivery_access(
  p_delivery_id bigint,
  p_token_hash text,
  p_xml_base64 text,
  p_chave_acesso text,
  p_backend_secret text
)
returns timestamptz
language sql
security invoker
set search_path = ''
as $$ select private.create_nfse_delivery_access_internal(p_delivery_id,p_token_hash,p_xml_base64,p_chave_acesso,p_backend_secret); $$;

revoke all on function private.create_nfse_delivery_access_internal(bigint,text,text,text,text) from public, anon;
grant execute on function private.create_nfse_delivery_access_internal(bigint,text,text,text,text) to authenticated;
revoke all on function public.create_nfse_delivery_access(bigint,text,text,text,text) from public, anon;
grant execute on function public.create_nfse_delivery_access(bigint,text,text,text,text) to authenticated;

create or replace function private.inspect_nfse_delivery_access_internal(p_token_hash text,p_backend_secret text)
returns table(valid boolean,competencia text,expires_at timestamptz,visualizado_em timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.valid_jpi_backend_secret(p_backend_secret) then
    raise exception 'Credencial interna do servidor inválida.' using errcode = '42501';
  end if;
  return query
  select l.expires_at > now(), m.competencia, l.expires_at, l.visualizado_em
  from private.nfse_entrega_links l
  join public.nfse_entregas e on e.id=l.entrega_id
  join public.mensalidades m on m.id=e.mensalidade_id
  where l.token_hash=p_token_hash;
end;
$$;

create or replace function public.inspect_nfse_delivery_access(p_token_hash text,p_backend_secret text)
returns table(valid boolean,competencia text,expires_at timestamptz,visualizado_em timestamptz)
language sql security invoker set search_path = ''
as $$ select * from private.inspect_nfse_delivery_access_internal(p_token_hash,p_backend_secret); $$;

revoke all on function private.inspect_nfse_delivery_access_internal(text,text) from public, anon, authenticated;
grant execute on function private.inspect_nfse_delivery_access_internal(text,text) to anon;
revoke all on function public.inspect_nfse_delivery_access(text,text) from public, authenticated;
grant execute on function public.inspect_nfse_delivery_access(text,text) to anon;

create or replace function private.open_nfse_delivery_access_internal(p_token_hash text,p_backend_secret text)
returns table(chave_acesso text,xml_base64 text,expires_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected private.nfse_entrega_links%rowtype;
  opened_at timestamptz := now();
begin
  if not private.valid_jpi_backend_secret(p_backend_secret) then
    raise exception 'Credencial interna do servidor inválida.' using errcode = '42501';
  end if;
  select * into selected from private.nfse_entrega_links
  where token_hash=p_token_hash and expires_at > opened_at for update;
  if not found then return; end if;
  update private.nfse_entrega_links set
    visualizado_em=coalesce(visualizado_em,opened_at), ultimo_acesso_em=opened_at,
    visualizacoes=visualizacoes+1 where id=selected.id;
  update public.nfse_entregas set
    visualizado_em=coalesce(visualizado_em,opened_at), visualizacoes=visualizacoes+1,
    updated_at=opened_at where id=selected.entrega_id;
  return query select selected.chave_acesso,encode(selected.xml_content,'base64'),selected.expires_at;
end;
$$;

create or replace function public.open_nfse_delivery_access(p_token_hash text,p_backend_secret text)
returns table(chave_acesso text,xml_base64 text,expires_at timestamptz)
language sql security invoker set search_path = ''
as $$ select * from private.open_nfse_delivery_access_internal(p_token_hash,p_backend_secret); $$;

revoke all on function private.open_nfse_delivery_access_internal(text,text) from public, anon, authenticated;
grant execute on function private.open_nfse_delivery_access_internal(text,text) to anon;
revoke all on function public.open_nfse_delivery_access(text,text) from public, authenticated;
grant execute on function public.open_nfse_delivery_access(text,text) to anon;

create or replace function private.read_nfse_delivery_access_internal(p_token_hash text,p_backend_secret text)
returns table(chave_acesso text,xml_base64 text,expires_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.valid_jpi_backend_secret(p_backend_secret) then
    raise exception 'Credencial interna do servidor inválida.' using errcode = '42501';
  end if;
  return query select l.chave_acesso,encode(l.xml_content,'base64'),l.expires_at
  from private.nfse_entrega_links l
  where l.token_hash=p_token_hash and l.expires_at > now() and l.visualizado_em is not null;
end;
$$;

create or replace function public.read_nfse_delivery_access(p_token_hash text,p_backend_secret text)
returns table(chave_acesso text,xml_base64 text,expires_at timestamptz)
language sql security invoker set search_path = ''
as $$ select * from private.read_nfse_delivery_access_internal(p_token_hash,p_backend_secret); $$;

revoke all on function private.read_nfse_delivery_access_internal(text,text) from public, anon, authenticated;
grant execute on function private.read_nfse_delivery_access_internal(text,text) to anon;
revoke all on function public.read_nfse_delivery_access(text,text) from public, authenticated;
grant execute on function public.read_nfse_delivery_access(text,text) to anon;

comment on table private.nfse_entrega_links is
  'Links individuais da Agenda Edu; guarda somente o hash do token e uma cópia privada do XML para acesso protegido.';
